/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCollectionsCollectionIndexRouteImport } from './routes/admin/collections/$collection/index'
import { Route as AdminApiCollectionIndexRouteImport } from './routes/admin/api/$collection/index'
import { Route as AdminCollectionsCollectionCreateRouteImport } from './routes/admin/collections/$collection/create'
import { Route as AdminCollectionsCollectionIdIndexRouteImport } from './routes/admin/collections/$collection/$id/index'
import { Route as AdminApiCollectionIdIndexRouteImport } from './routes/admin/api/$collection/$id/index'
import { Route as AdminCollectionsCollectionIdHistoryRouteImport } from './routes/admin/collections/$collection/$id/history'
import { Route as AdminCollectionsCollectionIdApiRouteImport } from './routes/admin/collections/$collection/$id/api'
import { Route as AdminApiCollectionIdPatchesRouteImport } from './routes/admin/api/$collection/$id/patches'
import { Route as AdminApiCollectionIdHistoryRouteImport } from './routes/admin/api/$collection/$id/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsCollectionIndexRoute =
  AdminCollectionsCollectionIndexRouteImport.update({
    id: '/admin/collections/$collection/',
    path: '/admin/collections/$collection/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminApiCollectionIndexRoute = AdminApiCollectionIndexRouteImport.update({
  id: '/admin/api/$collection/',
  path: '/admin/api/$collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsCollectionCreateRoute =
  AdminCollectionsCollectionCreateRouteImport.update({
    id: '/admin/collections/$collection/create',
    path: '/admin/collections/$collection/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCollectionsCollectionIdIndexRoute =
  AdminCollectionsCollectionIdIndexRouteImport.update({
    id: '/admin/collections/$collection/$id/',
    path: '/admin/collections/$collection/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminApiCollectionIdIndexRoute =
  AdminApiCollectionIdIndexRouteImport.update({
    id: '/admin/api/$collection/$id/',
    path: '/admin/api/$collection/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCollectionsCollectionIdHistoryRoute =
  AdminCollectionsCollectionIdHistoryRouteImport.update({
    id: '/admin/collections/$collection/$id/history',
    path: '/admin/collections/$collection/$id/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCollectionsCollectionIdApiRoute =
  AdminCollectionsCollectionIdApiRouteImport.update({
    id: '/admin/collections/$collection/$id/api',
    path: '/admin/collections/$collection/$id/api',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminApiCollectionIdPatchesRoute =
  AdminApiCollectionIdPatchesRouteImport.update({
    id: '/admin/api/$collection/$id/patches',
    path: '/admin/api/$collection/$id/patches',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminApiCollectionIdHistoryRoute =
  AdminApiCollectionIdHistoryRouteImport.update({
    id: '/admin/api/$collection/$id/history',
    path: '/admin/api/$collection/$id/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collections/$collection/create': typeof AdminCollectionsCollectionCreateRoute
  '/admin/api/$collection/': typeof AdminApiCollectionIndexRoute
  '/admin/collections/$collection/': typeof AdminCollectionsCollectionIndexRoute
  '/admin/api/$collection/$id/history': typeof AdminApiCollectionIdHistoryRoute
  '/admin/api/$collection/$id/patches': typeof AdminApiCollectionIdPatchesRoute
  '/admin/collections/$collection/$id/api': typeof AdminCollectionsCollectionIdApiRoute
  '/admin/collections/$collection/$id/history': typeof AdminCollectionsCollectionIdHistoryRoute
  '/admin/api/$collection/$id/': typeof AdminApiCollectionIdIndexRoute
  '/admin/collections/$collection/$id/': typeof AdminCollectionsCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/collections/$collection/create': typeof AdminCollectionsCollectionCreateRoute
  '/admin/api/$collection': typeof AdminApiCollectionIndexRoute
  '/admin/collections/$collection': typeof AdminCollectionsCollectionIndexRoute
  '/admin/api/$collection/$id/history': typeof AdminApiCollectionIdHistoryRoute
  '/admin/api/$collection/$id/patches': typeof AdminApiCollectionIdPatchesRoute
  '/admin/collections/$collection/$id/api': typeof AdminCollectionsCollectionIdApiRoute
  '/admin/collections/$collection/$id/history': typeof AdminCollectionsCollectionIdHistoryRoute
  '/admin/api/$collection/$id': typeof AdminApiCollectionIdIndexRoute
  '/admin/collections/$collection/$id': typeof AdminCollectionsCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collections/$collection/create': typeof AdminCollectionsCollectionCreateRoute
  '/admin/api/$collection/': typeof AdminApiCollectionIndexRoute
  '/admin/collections/$collection/': typeof AdminCollectionsCollectionIndexRoute
  '/admin/api/$collection/$id/history': typeof AdminApiCollectionIdHistoryRoute
  '/admin/api/$collection/$id/patches': typeof AdminApiCollectionIdPatchesRoute
  '/admin/collections/$collection/$id/api': typeof AdminCollectionsCollectionIdApiRoute
  '/admin/collections/$collection/$id/history': typeof AdminCollectionsCollectionIdHistoryRoute
  '/admin/api/$collection/$id/': typeof AdminApiCollectionIdIndexRoute
  '/admin/collections/$collection/$id/': typeof AdminCollectionsCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/'
    | '/admin/collections/$collection/create'
    | '/admin/api/$collection/'
    | '/admin/collections/$collection/'
    | '/admin/api/$collection/$id/history'
    | '/admin/api/$collection/$id/patches'
    | '/admin/collections/$collection/$id/api'
    | '/admin/collections/$collection/$id/history'
    | '/admin/api/$collection/$id/'
    | '/admin/collections/$collection/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/collections/$collection/create'
    | '/admin/api/$collection'
    | '/admin/collections/$collection'
    | '/admin/api/$collection/$id/history'
    | '/admin/api/$collection/$id/patches'
    | '/admin/collections/$collection/$id/api'
    | '/admin/collections/$collection/$id/history'
    | '/admin/api/$collection/$id'
    | '/admin/collections/$collection/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/admin/collections/$collection/create'
    | '/admin/api/$collection/'
    | '/admin/collections/$collection/'
    | '/admin/api/$collection/$id/history'
    | '/admin/api/$collection/$id/patches'
    | '/admin/collections/$collection/$id/api'
    | '/admin/collections/$collection/$id/history'
    | '/admin/api/$collection/$id/'
    | '/admin/collections/$collection/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCollectionsCollectionCreateRoute: typeof AdminCollectionsCollectionCreateRoute
  AdminApiCollectionIndexRoute: typeof AdminApiCollectionIndexRoute
  AdminCollectionsCollectionIndexRoute: typeof AdminCollectionsCollectionIndexRoute
  AdminApiCollectionIdHistoryRoute: typeof AdminApiCollectionIdHistoryRoute
  AdminApiCollectionIdPatchesRoute: typeof AdminApiCollectionIdPatchesRoute
  AdminCollectionsCollectionIdApiRoute: typeof AdminCollectionsCollectionIdApiRoute
  AdminCollectionsCollectionIdHistoryRoute: typeof AdminCollectionsCollectionIdHistoryRoute
  AdminApiCollectionIdIndexRoute: typeof AdminApiCollectionIdIndexRoute
  AdminCollectionsCollectionIdIndexRoute: typeof AdminCollectionsCollectionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/$collection/': {
      id: '/admin/collections/$collection/'
      path: '/admin/collections/$collection'
      fullPath: '/admin/collections/$collection/'
      preLoaderRoute: typeof AdminCollectionsCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api/$collection/': {
      id: '/admin/api/$collection/'
      path: '/admin/api/$collection'
      fullPath: '/admin/api/$collection/'
      preLoaderRoute: typeof AdminApiCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/$collection/create': {
      id: '/admin/collections/$collection/create'
      path: '/admin/collections/$collection/create'
      fullPath: '/admin/collections/$collection/create'
      preLoaderRoute: typeof AdminCollectionsCollectionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/$collection/$id/': {
      id: '/admin/collections/$collection/$id/'
      path: '/admin/collections/$collection/$id'
      fullPath: '/admin/collections/$collection/$id/'
      preLoaderRoute: typeof AdminCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api/$collection/$id/': {
      id: '/admin/api/$collection/$id/'
      path: '/admin/api/$collection/$id'
      fullPath: '/admin/api/$collection/$id/'
      preLoaderRoute: typeof AdminApiCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/$collection/$id/history': {
      id: '/admin/collections/$collection/$id/history'
      path: '/admin/collections/$collection/$id/history'
      fullPath: '/admin/collections/$collection/$id/history'
      preLoaderRoute: typeof AdminCollectionsCollectionIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/$collection/$id/api': {
      id: '/admin/collections/$collection/$id/api'
      path: '/admin/collections/$collection/$id/api'
      fullPath: '/admin/collections/$collection/$id/api'
      preLoaderRoute: typeof AdminCollectionsCollectionIdApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api/$collection/$id/patches': {
      id: '/admin/api/$collection/$id/patches'
      path: '/admin/api/$collection/$id/patches'
      fullPath: '/admin/api/$collection/$id/patches'
      preLoaderRoute: typeof AdminApiCollectionIdPatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api/$collection/$id/history': {
      id: '/admin/api/$collection/$id/history'
      path: '/admin/api/$collection/$id/history'
      fullPath: '/admin/api/$collection/$id/history'
      preLoaderRoute: typeof AdminApiCollectionIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCollectionsCollectionCreateRoute: AdminCollectionsCollectionCreateRoute,
  AdminApiCollectionIndexRoute: AdminApiCollectionIndexRoute,
  AdminCollectionsCollectionIndexRoute: AdminCollectionsCollectionIndexRoute,
  AdminApiCollectionIdHistoryRoute: AdminApiCollectionIdHistoryRoute,
  AdminApiCollectionIdPatchesRoute: AdminApiCollectionIdPatchesRoute,
  AdminCollectionsCollectionIdApiRoute: AdminCollectionsCollectionIdApiRoute,
  AdminCollectionsCollectionIdHistoryRoute:
    AdminCollectionsCollectionIdHistoryRoute,
  AdminApiCollectionIdIndexRoute: AdminApiCollectionIdIndexRoute,
  AdminCollectionsCollectionIdIndexRoute:
    AdminCollectionsCollectionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
