/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LngChar125RouteRouteImport } from './routes/{-$lng}/route'
import { Route as bylineSignInRouteImport } from './routes/(byline)/sign-in'
import { Route as Char123LngChar125PublicRouteRouteImport } from './routes/{-$lng}/_public/route'
import { Route as bylineAdminRouteRouteImport } from './routes/(byline)/admin/route'
import { Route as Char123LngChar125PublicIndexRouteImport } from './routes/{-$lng}/_public/index'
import { Route as bylineAdminIndexRouteImport } from './routes/(byline)/admin/index'
import { Route as bylineAdminUsersIndexRouteImport } from './routes/(byline)/admin/users/index'
import { Route as bylineAdminRolesIndexRouteImport } from './routes/(byline)/admin/roles/index'
import { Route as bylineAdminPermissionsIndexRouteImport } from './routes/(byline)/admin/permissions/index'
import { Route as bylineAdminAccountIndexRouteImport } from './routes/(byline)/admin/account/index'
import { Route as bylineAdminUsersIdIndexRouteImport } from './routes/(byline)/admin/users/$id/index'
import { Route as bylineAdminRolesIdIndexRouteImport } from './routes/(byline)/admin/roles/$id/index'
import { Route as bylineAdminCollectionsCollectionIndexRouteImport } from './routes/(byline)/admin/collections/$collection/index'
import { Route as bylineAdminCollectionsCollectionCreateRouteImport } from './routes/(byline)/admin/collections/$collection/create'
import { Route as bylineAdminCollectionsCollectionIdIndexRouteImport } from './routes/(byline)/admin/collections/$collection/$id/index'
import { Route as bylineAdminCollectionsCollectionIdHistoryRouteImport } from './routes/(byline)/admin/collections/$collection/$id/history'
import { Route as bylineAdminCollectionsCollectionIdApiRouteImport } from './routes/(byline)/admin/collections/$collection/$id/api'

const Char123LngChar125RouteRoute = Char123LngChar125RouteRouteImport.update({
  id: '/{-$lng}',
  path: '/{-$lng}',
  getParentRoute: () => rootRouteImport,
} as any)
const bylineSignInRoute = bylineSignInRouteImport.update({
  id: '/(byline)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LngChar125PublicRouteRoute =
  Char123LngChar125PublicRouteRouteImport.update({
    id: '/_public',
    getParentRoute: () => Char123LngChar125RouteRoute,
  } as any)
const bylineAdminRouteRoute = bylineAdminRouteRouteImport.update({
  id: '/(byline)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LngChar125PublicIndexRoute =
  Char123LngChar125PublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LngChar125PublicRouteRoute,
  } as any)
const bylineAdminIndexRoute = bylineAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => bylineAdminRouteRoute,
} as any)
const bylineAdminUsersIndexRoute = bylineAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => bylineAdminRouteRoute,
} as any)
const bylineAdminRolesIndexRoute = bylineAdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => bylineAdminRouteRoute,
} as any)
const bylineAdminPermissionsIndexRoute =
  bylineAdminPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => bylineAdminRouteRoute,
  } as any)
const bylineAdminAccountIndexRoute = bylineAdminAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => bylineAdminRouteRoute,
} as any)
const bylineAdminUsersIdIndexRoute = bylineAdminUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => bylineAdminRouteRoute,
} as any)
const bylineAdminRolesIdIndexRoute = bylineAdminRolesIdIndexRouteImport.update({
  id: '/roles/$id/',
  path: '/roles/$id/',
  getParentRoute: () => bylineAdminRouteRoute,
} as any)
const bylineAdminCollectionsCollectionIndexRoute =
  bylineAdminCollectionsCollectionIndexRouteImport.update({
    id: '/collections/$collection/',
    path: '/collections/$collection/',
    getParentRoute: () => bylineAdminRouteRoute,
  } as any)
const bylineAdminCollectionsCollectionCreateRoute =
  bylineAdminCollectionsCollectionCreateRouteImport.update({
    id: '/collections/$collection/create',
    path: '/collections/$collection/create',
    getParentRoute: () => bylineAdminRouteRoute,
  } as any)
const bylineAdminCollectionsCollectionIdIndexRoute =
  bylineAdminCollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collection/$id/',
    path: '/collections/$collection/$id/',
    getParentRoute: () => bylineAdminRouteRoute,
  } as any)
const bylineAdminCollectionsCollectionIdHistoryRoute =
  bylineAdminCollectionsCollectionIdHistoryRouteImport.update({
    id: '/collections/$collection/$id/history',
    path: '/collections/$collection/$id/history',
    getParentRoute: () => bylineAdminRouteRoute,
  } as any)
const bylineAdminCollectionsCollectionIdApiRoute =
  bylineAdminCollectionsCollectionIdApiRouteImport.update({
    id: '/collections/$collection/$id/api',
    path: '/collections/$collection/$id/api',
    getParentRoute: () => bylineAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$lng}': typeof Char123LngChar125PublicRouteRouteWithChildren
  '/admin': typeof bylineAdminRouteRouteWithChildren
  '/sign-in': typeof bylineSignInRoute
  '/admin/': typeof bylineAdminIndexRoute
  '/{-$lng}/': typeof Char123LngChar125PublicIndexRoute
  '/admin/account/': typeof bylineAdminAccountIndexRoute
  '/admin/permissions/': typeof bylineAdminPermissionsIndexRoute
  '/admin/roles/': typeof bylineAdminRolesIndexRoute
  '/admin/users/': typeof bylineAdminUsersIndexRoute
  '/admin/collections/$collection/create': typeof bylineAdminCollectionsCollectionCreateRoute
  '/admin/collections/$collection/': typeof bylineAdminCollectionsCollectionIndexRoute
  '/admin/roles/$id/': typeof bylineAdminRolesIdIndexRoute
  '/admin/users/$id/': typeof bylineAdminUsersIdIndexRoute
  '/admin/collections/$collection/$id/api': typeof bylineAdminCollectionsCollectionIdApiRoute
  '/admin/collections/$collection/$id/history': typeof bylineAdminCollectionsCollectionIdHistoryRoute
  '/admin/collections/$collection/$id/': typeof bylineAdminCollectionsCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/{-$lng}': typeof Char123LngChar125PublicIndexRoute
  '/sign-in': typeof bylineSignInRoute
  '/admin': typeof bylineAdminIndexRoute
  '/admin/account': typeof bylineAdminAccountIndexRoute
  '/admin/permissions': typeof bylineAdminPermissionsIndexRoute
  '/admin/roles': typeof bylineAdminRolesIndexRoute
  '/admin/users': typeof bylineAdminUsersIndexRoute
  '/admin/collections/$collection/create': typeof bylineAdminCollectionsCollectionCreateRoute
  '/admin/collections/$collection': typeof bylineAdminCollectionsCollectionIndexRoute
  '/admin/roles/$id': typeof bylineAdminRolesIdIndexRoute
  '/admin/users/$id': typeof bylineAdminUsersIdIndexRoute
  '/admin/collections/$collection/$id/api': typeof bylineAdminCollectionsCollectionIdApiRoute
  '/admin/collections/$collection/$id/history': typeof bylineAdminCollectionsCollectionIdHistoryRoute
  '/admin/collections/$collection/$id': typeof bylineAdminCollectionsCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lng}': typeof Char123LngChar125RouteRouteWithChildren
  '/(byline)/admin': typeof bylineAdminRouteRouteWithChildren
  '/{-$lng}/_public': typeof Char123LngChar125PublicRouteRouteWithChildren
  '/(byline)/sign-in': typeof bylineSignInRoute
  '/(byline)/admin/': typeof bylineAdminIndexRoute
  '/{-$lng}/_public/': typeof Char123LngChar125PublicIndexRoute
  '/(byline)/admin/account/': typeof bylineAdminAccountIndexRoute
  '/(byline)/admin/permissions/': typeof bylineAdminPermissionsIndexRoute
  '/(byline)/admin/roles/': typeof bylineAdminRolesIndexRoute
  '/(byline)/admin/users/': typeof bylineAdminUsersIndexRoute
  '/(byline)/admin/collections/$collection/create': typeof bylineAdminCollectionsCollectionCreateRoute
  '/(byline)/admin/collections/$collection/': typeof bylineAdminCollectionsCollectionIndexRoute
  '/(byline)/admin/roles/$id/': typeof bylineAdminRolesIdIndexRoute
  '/(byline)/admin/users/$id/': typeof bylineAdminUsersIdIndexRoute
  '/(byline)/admin/collections/$collection/$id/api': typeof bylineAdminCollectionsCollectionIdApiRoute
  '/(byline)/admin/collections/$collection/$id/history': typeof bylineAdminCollectionsCollectionIdHistoryRoute
  '/(byline)/admin/collections/$collection/$id/': typeof bylineAdminCollectionsCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lng}'
    | '/admin'
    | '/sign-in'
    | '/admin/'
    | '/{-$lng}/'
    | '/admin/account/'
    | '/admin/permissions/'
    | '/admin/roles/'
    | '/admin/users/'
    | '/admin/collections/$collection/create'
    | '/admin/collections/$collection/'
    | '/admin/roles/$id/'
    | '/admin/users/$id/'
    | '/admin/collections/$collection/$id/api'
    | '/admin/collections/$collection/$id/history'
    | '/admin/collections/$collection/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$lng}'
    | '/sign-in'
    | '/admin'
    | '/admin/account'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/collections/$collection/create'
    | '/admin/collections/$collection'
    | '/admin/roles/$id'
    | '/admin/users/$id'
    | '/admin/collections/$collection/$id/api'
    | '/admin/collections/$collection/$id/history'
    | '/admin/collections/$collection/$id'
  id:
    | '__root__'
    | '/{-$lng}'
    | '/(byline)/admin'
    | '/{-$lng}/_public'
    | '/(byline)/sign-in'
    | '/(byline)/admin/'
    | '/{-$lng}/_public/'
    | '/(byline)/admin/account/'
    | '/(byline)/admin/permissions/'
    | '/(byline)/admin/roles/'
    | '/(byline)/admin/users/'
    | '/(byline)/admin/collections/$collection/create'
    | '/(byline)/admin/collections/$collection/'
    | '/(byline)/admin/roles/$id/'
    | '/(byline)/admin/users/$id/'
    | '/(byline)/admin/collections/$collection/$id/api'
    | '/(byline)/admin/collections/$collection/$id/history'
    | '/(byline)/admin/collections/$collection/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LngChar125RouteRoute: typeof Char123LngChar125RouteRouteWithChildren
  bylineAdminRouteRoute: typeof bylineAdminRouteRouteWithChildren
  bylineSignInRoute: typeof bylineSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$lng}': {
      id: '/{-$lng}'
      path: '/{-$lng}'
      fullPath: '/{-$lng}'
      preLoaderRoute: typeof Char123LngChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(byline)/sign-in': {
      id: '/(byline)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof bylineSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lng}/_public': {
      id: '/{-$lng}/_public'
      path: ''
      fullPath: '/{-$lng}'
      preLoaderRoute: typeof Char123LngChar125PublicRouteRouteImport
      parentRoute: typeof Char123LngChar125RouteRoute
    }
    '/(byline)/admin': {
      id: '/(byline)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof bylineAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lng}/_public/': {
      id: '/{-$lng}/_public/'
      path: '/'
      fullPath: '/{-$lng}/'
      preLoaderRoute: typeof Char123LngChar125PublicIndexRouteImport
      parentRoute: typeof Char123LngChar125PublicRouteRoute
    }
    '/(byline)/admin/': {
      id: '/(byline)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof bylineAdminIndexRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/users/': {
      id: '/(byline)/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof bylineAdminUsersIndexRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/roles/': {
      id: '/(byline)/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof bylineAdminRolesIndexRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/permissions/': {
      id: '/(byline)/admin/permissions/'
      path: '/permissions'
      fullPath: '/admin/permissions/'
      preLoaderRoute: typeof bylineAdminPermissionsIndexRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/account/': {
      id: '/(byline)/admin/account/'
      path: '/account'
      fullPath: '/admin/account/'
      preLoaderRoute: typeof bylineAdminAccountIndexRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/users/$id/': {
      id: '/(byline)/admin/users/$id/'
      path: '/users/$id'
      fullPath: '/admin/users/$id/'
      preLoaderRoute: typeof bylineAdminUsersIdIndexRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/roles/$id/': {
      id: '/(byline)/admin/roles/$id/'
      path: '/roles/$id'
      fullPath: '/admin/roles/$id/'
      preLoaderRoute: typeof bylineAdminRolesIdIndexRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/collections/$collection/': {
      id: '/(byline)/admin/collections/$collection/'
      path: '/collections/$collection'
      fullPath: '/admin/collections/$collection/'
      preLoaderRoute: typeof bylineAdminCollectionsCollectionIndexRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/collections/$collection/create': {
      id: '/(byline)/admin/collections/$collection/create'
      path: '/collections/$collection/create'
      fullPath: '/admin/collections/$collection/create'
      preLoaderRoute: typeof bylineAdminCollectionsCollectionCreateRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/collections/$collection/$id/': {
      id: '/(byline)/admin/collections/$collection/$id/'
      path: '/collections/$collection/$id'
      fullPath: '/admin/collections/$collection/$id/'
      preLoaderRoute: typeof bylineAdminCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/collections/$collection/$id/history': {
      id: '/(byline)/admin/collections/$collection/$id/history'
      path: '/collections/$collection/$id/history'
      fullPath: '/admin/collections/$collection/$id/history'
      preLoaderRoute: typeof bylineAdminCollectionsCollectionIdHistoryRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
    '/(byline)/admin/collections/$collection/$id/api': {
      id: '/(byline)/admin/collections/$collection/$id/api'
      path: '/collections/$collection/$id/api'
      fullPath: '/admin/collections/$collection/$id/api'
      preLoaderRoute: typeof bylineAdminCollectionsCollectionIdApiRouteImport
      parentRoute: typeof bylineAdminRouteRoute
    }
  }
}

interface Char123LngChar125PublicRouteRouteChildren {
  Char123LngChar125PublicIndexRoute: typeof Char123LngChar125PublicIndexRoute
}

const Char123LngChar125PublicRouteRouteChildren: Char123LngChar125PublicRouteRouteChildren =
  {
    Char123LngChar125PublicIndexRoute: Char123LngChar125PublicIndexRoute,
  }

const Char123LngChar125PublicRouteRouteWithChildren =
  Char123LngChar125PublicRouteRoute._addFileChildren(
    Char123LngChar125PublicRouteRouteChildren,
  )

interface Char123LngChar125RouteRouteChildren {
  Char123LngChar125PublicRouteRoute: typeof Char123LngChar125PublicRouteRouteWithChildren
}

const Char123LngChar125RouteRouteChildren: Char123LngChar125RouteRouteChildren =
  {
    Char123LngChar125PublicRouteRoute:
      Char123LngChar125PublicRouteRouteWithChildren,
  }

const Char123LngChar125RouteRouteWithChildren =
  Char123LngChar125RouteRoute._addFileChildren(
    Char123LngChar125RouteRouteChildren,
  )

interface bylineAdminRouteRouteChildren {
  bylineAdminIndexRoute: typeof bylineAdminIndexRoute
  bylineAdminAccountIndexRoute: typeof bylineAdminAccountIndexRoute
  bylineAdminPermissionsIndexRoute: typeof bylineAdminPermissionsIndexRoute
  bylineAdminRolesIndexRoute: typeof bylineAdminRolesIndexRoute
  bylineAdminUsersIndexRoute: typeof bylineAdminUsersIndexRoute
  bylineAdminCollectionsCollectionCreateRoute: typeof bylineAdminCollectionsCollectionCreateRoute
  bylineAdminCollectionsCollectionIndexRoute: typeof bylineAdminCollectionsCollectionIndexRoute
  bylineAdminRolesIdIndexRoute: typeof bylineAdminRolesIdIndexRoute
  bylineAdminUsersIdIndexRoute: typeof bylineAdminUsersIdIndexRoute
  bylineAdminCollectionsCollectionIdApiRoute: typeof bylineAdminCollectionsCollectionIdApiRoute
  bylineAdminCollectionsCollectionIdHistoryRoute: typeof bylineAdminCollectionsCollectionIdHistoryRoute
  bylineAdminCollectionsCollectionIdIndexRoute: typeof bylineAdminCollectionsCollectionIdIndexRoute
}

const bylineAdminRouteRouteChildren: bylineAdminRouteRouteChildren = {
  bylineAdminIndexRoute: bylineAdminIndexRoute,
  bylineAdminAccountIndexRoute: bylineAdminAccountIndexRoute,
  bylineAdminPermissionsIndexRoute: bylineAdminPermissionsIndexRoute,
  bylineAdminRolesIndexRoute: bylineAdminRolesIndexRoute,
  bylineAdminUsersIndexRoute: bylineAdminUsersIndexRoute,
  bylineAdminCollectionsCollectionCreateRoute:
    bylineAdminCollectionsCollectionCreateRoute,
  bylineAdminCollectionsCollectionIndexRoute:
    bylineAdminCollectionsCollectionIndexRoute,
  bylineAdminRolesIdIndexRoute: bylineAdminRolesIdIndexRoute,
  bylineAdminUsersIdIndexRoute: bylineAdminUsersIdIndexRoute,
  bylineAdminCollectionsCollectionIdApiRoute:
    bylineAdminCollectionsCollectionIdApiRoute,
  bylineAdminCollectionsCollectionIdHistoryRoute:
    bylineAdminCollectionsCollectionIdHistoryRoute,
  bylineAdminCollectionsCollectionIdIndexRoute:
    bylineAdminCollectionsCollectionIdIndexRoute,
}

const bylineAdminRouteRouteWithChildren =
  bylineAdminRouteRoute._addFileChildren(bylineAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LngChar125RouteRoute: Char123LngChar125RouteRouteWithChildren,
  bylineAdminRouteRoute: bylineAdminRouteRouteWithChildren,
  bylineSignInRoute: bylineSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
