/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LngChar125RouteRouteImport } from './routes/{-$lng}/route'
import { Route as Char123LngChar125PublicRouteRouteImport } from './routes/{-$lng}/_public/route'
import { Route as Char123LngChar125PublicIndexRouteImport } from './routes/{-$lng}/_public/index'
import { Route as Char123LngChar125bylineSignInRouteImport } from './routes/{-$lng}/(byline)/sign-in'
import { Route as Char123LngChar125bylineAdminRouteRouteImport } from './routes/{-$lng}/(byline)/admin/route'
import { Route as Char123LngChar125bylineAdminIndexRouteImport } from './routes/{-$lng}/(byline)/admin/index'
import { Route as Char123LngChar125bylineAdminUsersIndexRouteImport } from './routes/{-$lng}/(byline)/admin/users/index'
import { Route as Char123LngChar125bylineAdminRolesIndexRouteImport } from './routes/{-$lng}/(byline)/admin/roles/index'
import { Route as Char123LngChar125bylineAdminPermissionsIndexRouteImport } from './routes/{-$lng}/(byline)/admin/permissions/index'
import { Route as Char123LngChar125bylineAdminAccountIndexRouteImport } from './routes/{-$lng}/(byline)/admin/account/index'
import { Route as Char123LngChar125bylineAdminCollectionsCollectionIndexRouteImport } from './routes/{-$lng}/(byline)/admin/collections/$collection/index'
import { Route as Char123LngChar125bylineAdminCollectionsCollectionCreateRouteImport } from './routes/{-$lng}/(byline)/admin/collections/$collection/create'
import { Route as Char123LngChar125bylineAdminCollectionsCollectionIdIndexRouteImport } from './routes/{-$lng}/(byline)/admin/collections/$collection/$id/index'
import { Route as Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRouteImport } from './routes/{-$lng}/(byline)/admin/collections/$collection/$id/history'
import { Route as Char123LngChar125bylineAdminCollectionsCollectionIdApiRouteImport } from './routes/{-$lng}/(byline)/admin/collections/$collection/$id/api'

const Char123LngChar125RouteRoute = Char123LngChar125RouteRouteImport.update({
  id: '/{-$lng}',
  path: '/{-$lng}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LngChar125PublicRouteRoute =
  Char123LngChar125PublicRouteRouteImport.update({
    id: '/_public',
    getParentRoute: () => Char123LngChar125RouteRoute,
  } as any)
const Char123LngChar125PublicIndexRoute =
  Char123LngChar125PublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LngChar125PublicRouteRoute,
  } as any)
const Char123LngChar125bylineSignInRoute =
  Char123LngChar125bylineSignInRouteImport.update({
    id: '/(byline)/sign-in',
    path: '/sign-in',
    getParentRoute: () => Char123LngChar125RouteRoute,
  } as any)
const Char123LngChar125bylineAdminRouteRoute =
  Char123LngChar125bylineAdminRouteRouteImport.update({
    id: '/(byline)/admin',
    path: '/admin',
    getParentRoute: () => Char123LngChar125RouteRoute,
  } as any)
const Char123LngChar125bylineAdminIndexRoute =
  Char123LngChar125bylineAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LngChar125bylineAdminRouteRoute,
  } as any)
const Char123LngChar125bylineAdminUsersIndexRoute =
  Char123LngChar125bylineAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => Char123LngChar125bylineAdminRouteRoute,
  } as any)
const Char123LngChar125bylineAdminRolesIndexRoute =
  Char123LngChar125bylineAdminRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => Char123LngChar125bylineAdminRouteRoute,
  } as any)
const Char123LngChar125bylineAdminPermissionsIndexRoute =
  Char123LngChar125bylineAdminPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => Char123LngChar125bylineAdminRouteRoute,
  } as any)
const Char123LngChar125bylineAdminAccountIndexRoute =
  Char123LngChar125bylineAdminAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => Char123LngChar125bylineAdminRouteRoute,
  } as any)
const Char123LngChar125bylineAdminCollectionsCollectionIndexRoute =
  Char123LngChar125bylineAdminCollectionsCollectionIndexRouteImport.update({
    id: '/collections/$collection/',
    path: '/collections/$collection/',
    getParentRoute: () => Char123LngChar125bylineAdminRouteRoute,
  } as any)
const Char123LngChar125bylineAdminCollectionsCollectionCreateRoute =
  Char123LngChar125bylineAdminCollectionsCollectionCreateRouteImport.update({
    id: '/collections/$collection/create',
    path: '/collections/$collection/create',
    getParentRoute: () => Char123LngChar125bylineAdminRouteRoute,
  } as any)
const Char123LngChar125bylineAdminCollectionsCollectionIdIndexRoute =
  Char123LngChar125bylineAdminCollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collection/$id/',
    path: '/collections/$collection/$id/',
    getParentRoute: () => Char123LngChar125bylineAdminRouteRoute,
  } as any)
const Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRoute =
  Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRouteImport.update({
    id: '/collections/$collection/$id/history',
    path: '/collections/$collection/$id/history',
    getParentRoute: () => Char123LngChar125bylineAdminRouteRoute,
  } as any)
const Char123LngChar125bylineAdminCollectionsCollectionIdApiRoute =
  Char123LngChar125bylineAdminCollectionsCollectionIdApiRouteImport.update({
    id: '/collections/$collection/$id/api',
    path: '/collections/$collection/$id/api',
    getParentRoute: () => Char123LngChar125bylineAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$lng}': typeof Char123LngChar125PublicRouteRouteWithChildren
  '/{-$lng}/admin': typeof Char123LngChar125bylineAdminRouteRouteWithChildren
  '/{-$lng}/sign-in': typeof Char123LngChar125bylineSignInRoute
  '/{-$lng}/': typeof Char123LngChar125PublicIndexRoute
  '/{-$lng}/admin/': typeof Char123LngChar125bylineAdminIndexRoute
  '/{-$lng}/admin/account/': typeof Char123LngChar125bylineAdminAccountIndexRoute
  '/{-$lng}/admin/permissions/': typeof Char123LngChar125bylineAdminPermissionsIndexRoute
  '/{-$lng}/admin/roles/': typeof Char123LngChar125bylineAdminRolesIndexRoute
  '/{-$lng}/admin/users/': typeof Char123LngChar125bylineAdminUsersIndexRoute
  '/{-$lng}/admin/collections/$collection/create': typeof Char123LngChar125bylineAdminCollectionsCollectionCreateRoute
  '/{-$lng}/admin/collections/$collection/': typeof Char123LngChar125bylineAdminCollectionsCollectionIndexRoute
  '/{-$lng}/admin/collections/$collection/$id/api': typeof Char123LngChar125bylineAdminCollectionsCollectionIdApiRoute
  '/{-$lng}/admin/collections/$collection/$id/history': typeof Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRoute
  '/{-$lng}/admin/collections/$collection/$id/': typeof Char123LngChar125bylineAdminCollectionsCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/{-$lng}': typeof Char123LngChar125PublicIndexRoute
  '/{-$lng}/sign-in': typeof Char123LngChar125bylineSignInRoute
  '/{-$lng}/admin': typeof Char123LngChar125bylineAdminIndexRoute
  '/{-$lng}/admin/account': typeof Char123LngChar125bylineAdminAccountIndexRoute
  '/{-$lng}/admin/permissions': typeof Char123LngChar125bylineAdminPermissionsIndexRoute
  '/{-$lng}/admin/roles': typeof Char123LngChar125bylineAdminRolesIndexRoute
  '/{-$lng}/admin/users': typeof Char123LngChar125bylineAdminUsersIndexRoute
  '/{-$lng}/admin/collections/$collection/create': typeof Char123LngChar125bylineAdminCollectionsCollectionCreateRoute
  '/{-$lng}/admin/collections/$collection': typeof Char123LngChar125bylineAdminCollectionsCollectionIndexRoute
  '/{-$lng}/admin/collections/$collection/$id/api': typeof Char123LngChar125bylineAdminCollectionsCollectionIdApiRoute
  '/{-$lng}/admin/collections/$collection/$id/history': typeof Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRoute
  '/{-$lng}/admin/collections/$collection/$id': typeof Char123LngChar125bylineAdminCollectionsCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lng}': typeof Char123LngChar125RouteRouteWithChildren
  '/{-$lng}/_public': typeof Char123LngChar125PublicRouteRouteWithChildren
  '/{-$lng}/(byline)/admin': typeof Char123LngChar125bylineAdminRouteRouteWithChildren
  '/{-$lng}/(byline)/sign-in': typeof Char123LngChar125bylineSignInRoute
  '/{-$lng}/_public/': typeof Char123LngChar125PublicIndexRoute
  '/{-$lng}/(byline)/admin/': typeof Char123LngChar125bylineAdminIndexRoute
  '/{-$lng}/(byline)/admin/account/': typeof Char123LngChar125bylineAdminAccountIndexRoute
  '/{-$lng}/(byline)/admin/permissions/': typeof Char123LngChar125bylineAdminPermissionsIndexRoute
  '/{-$lng}/(byline)/admin/roles/': typeof Char123LngChar125bylineAdminRolesIndexRoute
  '/{-$lng}/(byline)/admin/users/': typeof Char123LngChar125bylineAdminUsersIndexRoute
  '/{-$lng}/(byline)/admin/collections/$collection/create': typeof Char123LngChar125bylineAdminCollectionsCollectionCreateRoute
  '/{-$lng}/(byline)/admin/collections/$collection/': typeof Char123LngChar125bylineAdminCollectionsCollectionIndexRoute
  '/{-$lng}/(byline)/admin/collections/$collection/$id/api': typeof Char123LngChar125bylineAdminCollectionsCollectionIdApiRoute
  '/{-$lng}/(byline)/admin/collections/$collection/$id/history': typeof Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRoute
  '/{-$lng}/(byline)/admin/collections/$collection/$id/': typeof Char123LngChar125bylineAdminCollectionsCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lng}'
    | '/{-$lng}/admin'
    | '/{-$lng}/sign-in'
    | '/{-$lng}/'
    | '/{-$lng}/admin/'
    | '/{-$lng}/admin/account/'
    | '/{-$lng}/admin/permissions/'
    | '/{-$lng}/admin/roles/'
    | '/{-$lng}/admin/users/'
    | '/{-$lng}/admin/collections/$collection/create'
    | '/{-$lng}/admin/collections/$collection/'
    | '/{-$lng}/admin/collections/$collection/$id/api'
    | '/{-$lng}/admin/collections/$collection/$id/history'
    | '/{-$lng}/admin/collections/$collection/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$lng}'
    | '/{-$lng}/sign-in'
    | '/{-$lng}/admin'
    | '/{-$lng}/admin/account'
    | '/{-$lng}/admin/permissions'
    | '/{-$lng}/admin/roles'
    | '/{-$lng}/admin/users'
    | '/{-$lng}/admin/collections/$collection/create'
    | '/{-$lng}/admin/collections/$collection'
    | '/{-$lng}/admin/collections/$collection/$id/api'
    | '/{-$lng}/admin/collections/$collection/$id/history'
    | '/{-$lng}/admin/collections/$collection/$id'
  id:
    | '__root__'
    | '/{-$lng}'
    | '/{-$lng}/_public'
    | '/{-$lng}/(byline)/admin'
    | '/{-$lng}/(byline)/sign-in'
    | '/{-$lng}/_public/'
    | '/{-$lng}/(byline)/admin/'
    | '/{-$lng}/(byline)/admin/account/'
    | '/{-$lng}/(byline)/admin/permissions/'
    | '/{-$lng}/(byline)/admin/roles/'
    | '/{-$lng}/(byline)/admin/users/'
    | '/{-$lng}/(byline)/admin/collections/$collection/create'
    | '/{-$lng}/(byline)/admin/collections/$collection/'
    | '/{-$lng}/(byline)/admin/collections/$collection/$id/api'
    | '/{-$lng}/(byline)/admin/collections/$collection/$id/history'
    | '/{-$lng}/(byline)/admin/collections/$collection/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LngChar125RouteRoute: typeof Char123LngChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$lng}': {
      id: '/{-$lng}'
      path: '/{-$lng}'
      fullPath: '/{-$lng}'
      preLoaderRoute: typeof Char123LngChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lng}/_public': {
      id: '/{-$lng}/_public'
      path: ''
      fullPath: '/{-$lng}'
      preLoaderRoute: typeof Char123LngChar125PublicRouteRouteImport
      parentRoute: typeof Char123LngChar125RouteRoute
    }
    '/{-$lng}/_public/': {
      id: '/{-$lng}/_public/'
      path: '/'
      fullPath: '/{-$lng}/'
      preLoaderRoute: typeof Char123LngChar125PublicIndexRouteImport
      parentRoute: typeof Char123LngChar125PublicRouteRoute
    }
    '/{-$lng}/(byline)/sign-in': {
      id: '/{-$lng}/(byline)/sign-in'
      path: '/sign-in'
      fullPath: '/{-$lng}/sign-in'
      preLoaderRoute: typeof Char123LngChar125bylineSignInRouteImport
      parentRoute: typeof Char123LngChar125RouteRoute
    }
    '/{-$lng}/(byline)/admin': {
      id: '/{-$lng}/(byline)/admin'
      path: '/admin'
      fullPath: '/{-$lng}/admin'
      preLoaderRoute: typeof Char123LngChar125bylineAdminRouteRouteImport
      parentRoute: typeof Char123LngChar125RouteRoute
    }
    '/{-$lng}/(byline)/admin/': {
      id: '/{-$lng}/(byline)/admin/'
      path: '/'
      fullPath: '/{-$lng}/admin/'
      preLoaderRoute: typeof Char123LngChar125bylineAdminIndexRouteImport
      parentRoute: typeof Char123LngChar125bylineAdminRouteRoute
    }
    '/{-$lng}/(byline)/admin/users/': {
      id: '/{-$lng}/(byline)/admin/users/'
      path: '/users'
      fullPath: '/{-$lng}/admin/users/'
      preLoaderRoute: typeof Char123LngChar125bylineAdminUsersIndexRouteImport
      parentRoute: typeof Char123LngChar125bylineAdminRouteRoute
    }
    '/{-$lng}/(byline)/admin/roles/': {
      id: '/{-$lng}/(byline)/admin/roles/'
      path: '/roles'
      fullPath: '/{-$lng}/admin/roles/'
      preLoaderRoute: typeof Char123LngChar125bylineAdminRolesIndexRouteImport
      parentRoute: typeof Char123LngChar125bylineAdminRouteRoute
    }
    '/{-$lng}/(byline)/admin/permissions/': {
      id: '/{-$lng}/(byline)/admin/permissions/'
      path: '/permissions'
      fullPath: '/{-$lng}/admin/permissions/'
      preLoaderRoute: typeof Char123LngChar125bylineAdminPermissionsIndexRouteImport
      parentRoute: typeof Char123LngChar125bylineAdminRouteRoute
    }
    '/{-$lng}/(byline)/admin/account/': {
      id: '/{-$lng}/(byline)/admin/account/'
      path: '/account'
      fullPath: '/{-$lng}/admin/account/'
      preLoaderRoute: typeof Char123LngChar125bylineAdminAccountIndexRouteImport
      parentRoute: typeof Char123LngChar125bylineAdminRouteRoute
    }
    '/{-$lng}/(byline)/admin/collections/$collection/': {
      id: '/{-$lng}/(byline)/admin/collections/$collection/'
      path: '/collections/$collection'
      fullPath: '/{-$lng}/admin/collections/$collection/'
      preLoaderRoute: typeof Char123LngChar125bylineAdminCollectionsCollectionIndexRouteImport
      parentRoute: typeof Char123LngChar125bylineAdminRouteRoute
    }
    '/{-$lng}/(byline)/admin/collections/$collection/create': {
      id: '/{-$lng}/(byline)/admin/collections/$collection/create'
      path: '/collections/$collection/create'
      fullPath: '/{-$lng}/admin/collections/$collection/create'
      preLoaderRoute: typeof Char123LngChar125bylineAdminCollectionsCollectionCreateRouteImport
      parentRoute: typeof Char123LngChar125bylineAdminRouteRoute
    }
    '/{-$lng}/(byline)/admin/collections/$collection/$id/': {
      id: '/{-$lng}/(byline)/admin/collections/$collection/$id/'
      path: '/collections/$collection/$id'
      fullPath: '/{-$lng}/admin/collections/$collection/$id/'
      preLoaderRoute: typeof Char123LngChar125bylineAdminCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof Char123LngChar125bylineAdminRouteRoute
    }
    '/{-$lng}/(byline)/admin/collections/$collection/$id/history': {
      id: '/{-$lng}/(byline)/admin/collections/$collection/$id/history'
      path: '/collections/$collection/$id/history'
      fullPath: '/{-$lng}/admin/collections/$collection/$id/history'
      preLoaderRoute: typeof Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRouteImport
      parentRoute: typeof Char123LngChar125bylineAdminRouteRoute
    }
    '/{-$lng}/(byline)/admin/collections/$collection/$id/api': {
      id: '/{-$lng}/(byline)/admin/collections/$collection/$id/api'
      path: '/collections/$collection/$id/api'
      fullPath: '/{-$lng}/admin/collections/$collection/$id/api'
      preLoaderRoute: typeof Char123LngChar125bylineAdminCollectionsCollectionIdApiRouteImport
      parentRoute: typeof Char123LngChar125bylineAdminRouteRoute
    }
  }
}

interface Char123LngChar125PublicRouteRouteChildren {
  Char123LngChar125PublicIndexRoute: typeof Char123LngChar125PublicIndexRoute
}

const Char123LngChar125PublicRouteRouteChildren: Char123LngChar125PublicRouteRouteChildren =
  {
    Char123LngChar125PublicIndexRoute: Char123LngChar125PublicIndexRoute,
  }

const Char123LngChar125PublicRouteRouteWithChildren =
  Char123LngChar125PublicRouteRoute._addFileChildren(
    Char123LngChar125PublicRouteRouteChildren,
  )

interface Char123LngChar125bylineAdminRouteRouteChildren {
  Char123LngChar125bylineAdminIndexRoute: typeof Char123LngChar125bylineAdminIndexRoute
  Char123LngChar125bylineAdminAccountIndexRoute: typeof Char123LngChar125bylineAdminAccountIndexRoute
  Char123LngChar125bylineAdminPermissionsIndexRoute: typeof Char123LngChar125bylineAdminPermissionsIndexRoute
  Char123LngChar125bylineAdminRolesIndexRoute: typeof Char123LngChar125bylineAdminRolesIndexRoute
  Char123LngChar125bylineAdminUsersIndexRoute: typeof Char123LngChar125bylineAdminUsersIndexRoute
  Char123LngChar125bylineAdminCollectionsCollectionCreateRoute: typeof Char123LngChar125bylineAdminCollectionsCollectionCreateRoute
  Char123LngChar125bylineAdminCollectionsCollectionIndexRoute: typeof Char123LngChar125bylineAdminCollectionsCollectionIndexRoute
  Char123LngChar125bylineAdminCollectionsCollectionIdApiRoute: typeof Char123LngChar125bylineAdminCollectionsCollectionIdApiRoute
  Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRoute: typeof Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRoute
  Char123LngChar125bylineAdminCollectionsCollectionIdIndexRoute: typeof Char123LngChar125bylineAdminCollectionsCollectionIdIndexRoute
}

const Char123LngChar125bylineAdminRouteRouteChildren: Char123LngChar125bylineAdminRouteRouteChildren =
  {
    Char123LngChar125bylineAdminIndexRoute:
      Char123LngChar125bylineAdminIndexRoute,
    Char123LngChar125bylineAdminAccountIndexRoute:
      Char123LngChar125bylineAdminAccountIndexRoute,
    Char123LngChar125bylineAdminPermissionsIndexRoute:
      Char123LngChar125bylineAdminPermissionsIndexRoute,
    Char123LngChar125bylineAdminRolesIndexRoute:
      Char123LngChar125bylineAdminRolesIndexRoute,
    Char123LngChar125bylineAdminUsersIndexRoute:
      Char123LngChar125bylineAdminUsersIndexRoute,
    Char123LngChar125bylineAdminCollectionsCollectionCreateRoute:
      Char123LngChar125bylineAdminCollectionsCollectionCreateRoute,
    Char123LngChar125bylineAdminCollectionsCollectionIndexRoute:
      Char123LngChar125bylineAdminCollectionsCollectionIndexRoute,
    Char123LngChar125bylineAdminCollectionsCollectionIdApiRoute:
      Char123LngChar125bylineAdminCollectionsCollectionIdApiRoute,
    Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRoute:
      Char123LngChar125bylineAdminCollectionsCollectionIdHistoryRoute,
    Char123LngChar125bylineAdminCollectionsCollectionIdIndexRoute:
      Char123LngChar125bylineAdminCollectionsCollectionIdIndexRoute,
  }

const Char123LngChar125bylineAdminRouteRouteWithChildren =
  Char123LngChar125bylineAdminRouteRoute._addFileChildren(
    Char123LngChar125bylineAdminRouteRouteChildren,
  )

interface Char123LngChar125RouteRouteChildren {
  Char123LngChar125PublicRouteRoute: typeof Char123LngChar125PublicRouteRouteWithChildren
  Char123LngChar125bylineAdminRouteRoute: typeof Char123LngChar125bylineAdminRouteRouteWithChildren
  Char123LngChar125bylineSignInRoute: typeof Char123LngChar125bylineSignInRoute
}

const Char123LngChar125RouteRouteChildren: Char123LngChar125RouteRouteChildren =
  {
    Char123LngChar125PublicRouteRoute:
      Char123LngChar125PublicRouteRouteWithChildren,
    Char123LngChar125bylineAdminRouteRoute:
      Char123LngChar125bylineAdminRouteRouteWithChildren,
    Char123LngChar125bylineSignInRoute: Char123LngChar125bylineSignInRoute,
  }

const Char123LngChar125RouteRouteWithChildren =
  Char123LngChar125RouteRoute._addFileChildren(
    Char123LngChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LngChar125RouteRoute: Char123LngChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
