import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

import { buildPgUrl } from '../lib/pg-url.js'
import { ENV_SPECS, type EnvKey } from '../manifest/env.js'
import type { Context } from '../context.js'
import type { Phase } from '../types.js'

export const envPhase: Phase = {
  id: 'env',
  title: 'Env — generate .env (JWT secret, admin credentials, DB connection)',
  defaultMode: 'confirm',

  async detect(ctx) {
    if (ctx.state.isComplete('env')) return 'done'
    const a = ctx.state.get().answers
    if (!a.dbHost || !a.dbName || !a.dbUser) return 'blocked'
    return 'pending'
  },

  async plan(ctx) {
    const envPath = ctx.resolve('.env')
    const existing = readEnvFile(envPath)
    const missing = ENV_SPECS.filter((s) => !existing[s.key])

    const notes: string[] = []
    if (existsSync(envPath)) {
      notes.push(`.env exists — preserving existing keys, appending what is missing`)
    } else {
      notes.push('.env does not exist — will create')
    }
    if (missing.length === 0) {
      notes.push('all required keys already present — nothing to do')
    } else {
      for (const s of missing) notes.push(`  + ${s.key}  (${s.description})`)
    }
    return { writes: [], commands: [], notes }
  },

  async apply(_plan, ctx) {
    const envPath = ctx.resolve('.env')
    const existing = readEnvFile(envPath)
    const missing = new Set<EnvKey>(ENV_SPECS.filter((s) => !existing[s.key]).map((s) => s.key))

    if (missing.size === 0) {
      ctx.logger.info('all required env vars already set — leaving .env unchanged')
      return { state: 'done' }
    }

    const a = ctx.state.get().answers
    if (!a.dbHost || !a.dbName || !a.dbUser) {
      ctx.logger.error('db answers missing — run the db phase first')
      return { state: 'blocked' }
    }

    const values: Record<string, string> = { ...existing }

    if (missing.has('VITE_SERVER_URL')) {
      ctx.prompter.note(
        [
          'The URL where this installation will be running.',
          'Used by SSR rendering and as the base for admin UI links.',
          'For local dev the default is fine; in production set this to your',
          'public origin (e.g. https://cms.example.com).',
        ].join('\n'),
        'VITE_SERVER_URL'
      )
      values.VITE_SERVER_URL = await ctx.prompter.text({
        message: 'Public origin URL',
        placeholder: 'http://localhost:5173/',
        defaultValue: 'http://localhost:5173/',
      })
    }

    if (missing.has('BYLINE_JWT_SECRET')) {
      values.BYLINE_JWT_SECRET = randomBytes(64).toString('base64url')
      ctx.logger.step('generated BYLINE_JWT_SECRET (64 random bytes, base64url)')
    }

    if (missing.has('BYLINE_SUPERADMIN_EMAIL')) {
      const email = await ctx.prompter.text({
        message: 'Super-admin email',
        defaultValue: a.adminEmail ?? 'admin@byline.local',
      })
      ctx.state.patchAnswers({ adminEmail: email })
      values.BYLINE_SUPERADMIN_EMAIL = email
    }

    if (missing.has('BYLINE_SUPERADMIN_PASSWORD')) {
      const pw = await ctx.prompter.password({
        message: 'Super-admin password (min 8 chars)',
        validate: (v) => (v.length < 8 ? 'must be at least 8 characters' : undefined),
      })
      values.BYLINE_SUPERADMIN_PASSWORD = pw
    }

    if (missing.has('DB_CONNECTION_STRING')) {
      const dbPassword = await resolveDbPassword(ctx)
      if (!dbPassword) return { state: 'blocked' }
      values.DB_CONNECTION_STRING = buildPgUrl({
        host: a.dbHost,
        port: a.dbPort ?? 5432,
        user: a.dbUser,
        password: dbPassword,
        database: a.dbName,
      })
    }

    writeFileSync(envPath, renderEnvFile(values), 'utf8')
    ctx.logger.success(`wrote ${envPath}`)
    return { state: 'done' }
  },
}

async function resolveDbPassword(ctx: Context): Promise<string | null> {
  if (ctx.secrets.dbPassword) return ctx.secrets.dbPassword
  const fromEnv = process.env.BYLINE_DB_PASSWORD
  if (fromEnv) {
    ctx.logger.info('using app role password from BYLINE_DB_PASSWORD')
    return fromEnv
  }
  const pw = await ctx.prompter.password({
    message: 'Application database role password (re-enter to compose DB_CONNECTION_STRING)',
  })
  if (!pw) {
    ctx.logger.error('password is required to compose DB_CONNECTION_STRING')
    return null
  }
  ctx.secrets.dbPassword = pw
  return pw
}

function readEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {}
  const out: Record<string, string> = {}
  const raw = readFileSync(path, 'utf8')
  for (const line of raw.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$/)
    if (!m) continue
    const key = m[1] as string
    let val = (m[2] ?? '').trim()
    if (val.startsWith('"') && val.endsWith('"')) {
      val = val.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\')
    } else if (val.startsWith("'") && val.endsWith("'")) {
      val = val.slice(1, -1)
    }
    out[key] = val
  }
  return out
}

function renderEnvFile(values: Record<string, string>): string {
  const known = new Set<string>(ENV_SPECS.map((s) => s.key))
  const groups: Record<'app' | 'database' | 'auth', string[]> = { app: [], database: [], auth: [] }
  for (const spec of ENV_SPECS) {
    const v = values[spec.key]
    if (v === undefined) continue
    groups[spec.group].push(`# ${spec.description}\n${spec.key}=${formatEnvValue(v)}`)
  }

  const sections: string[] = []
  if (groups.app.length) sections.push(`# App\n${groups.app.join('\n\n')}`)
  if (groups.database.length) sections.push(`# Database\n${groups.database.join('\n\n')}`)
  if (groups.auth.length) sections.push(`# Auth\n${groups.auth.join('\n\n')}`)

  const extras = Object.entries(values)
    .filter(([k]) => !known.has(k))
    .map(([k, v]) => `${k}=${formatEnvValue(v)}`)
  if (extras.length) sections.push(`# Existing\n${extras.join('\n')}`)

  return `${sections.join('\n\n')}\n`
}

function formatEnvValue(v: string): string {
  if (v === '') return ''
  if (/^[A-Za-z0-9_\-./:@+]+$/.test(v)) return v
  return `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}
