import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

import { buildPgUrl } from '../lib/pg-url.js'
import { ENV_FILE_PATHS, ENV_SPECS, type EnvFile, type EnvKey } from '../manifest/env.js'
import type { Context } from '../context.js'
import type { Phase } from '../types.js'

export const envPhase: Phase = {
  id: 'env',
  title: 'Env — generate .env (public defaults) and .env.local (secrets: JWT, admin creds, DB URL)',
  defaultMode: 'confirm',

  async detect(ctx) {
    if (ctx.state.isComplete('env')) return 'done'
    const a = ctx.state.get().answers
    if (!a.dbHost || !a.dbName || !a.dbUser) return 'blocked'
    return 'pending'
  },

  async plan(ctx) {
    const existing = readAllEnvFiles(ctx)
    const missing = ENV_SPECS.filter((s) => !existing[s.file][s.key])

    const notes: string[] = []
    for (const file of Object.keys(ENV_FILE_PATHS) as EnvFile[]) {
      const path = ctx.resolve(ENV_FILE_PATHS[file])
      if (existsSync(path)) {
        notes.push(
          `${ENV_FILE_PATHS[file]} exists — preserving existing keys, appending what is missing`
        )
      } else {
        notes.push(`${ENV_FILE_PATHS[file]} does not exist — will create`)
      }
    }
    if (missing.length === 0) {
      notes.push('all required keys already present — nothing to do')
    } else {
      for (const s of missing) {
        notes.push(`  + ${s.key}  →  ${ENV_FILE_PATHS[s.file]}  (${s.description})`)
      }
    }
    return { writes: [], commands: [], notes }
  },

  async apply(_plan, ctx) {
    const existing = readAllEnvFiles(ctx)
    const missing = new Set<EnvKey>(
      ENV_SPECS.filter((s) => !existing[s.file][s.key]).map((s) => s.key)
    )

    if (missing.size === 0) {
      ctx.logger.info('all required env vars already set — leaving .env / .env.local unchanged')
      return { state: 'done' }
    }

    const a = ctx.state.get().answers
    if (!a.dbHost || !a.dbName || !a.dbUser) {
      ctx.logger.error('db answers missing — run the db phase first')
      return { state: 'blocked' }
    }

    const values: Record<EnvFile, Record<string, string>> = {
      public: { ...existing.public },
      secret: { ...existing.secret },
    }

    if (missing.has('VITE_SERVER_URL')) {
      ctx.prompter.note(
        [
          'The URL where this installation will be running.',
          'Used by SSR rendering and as the base for admin UI links.',
          'For local dev the default is fine; in production set this to your',
          'public origin (e.g. https://cms.example.com).',
        ].join('\n'),
        'VITE_SERVER_URL'
      )
      values.public.VITE_SERVER_URL = await ctx.prompter.text({
        message: 'Public origin URL',
        placeholder: 'http://localhost:3000/',
        defaultValue: 'http://localhost:3000/',
      })
    }

    if (missing.has('BYLINE_JWT_SECRET')) {
      values.secret.BYLINE_JWT_SECRET = randomBytes(64).toString('base64url')
      ctx.logger.step('generated BYLINE_JWT_SECRET (64 random bytes, base64url)')
    }

    if (missing.has('BYLINE_SUPERADMIN_EMAIL')) {
      const email = await ctx.prompter.text({
        message: 'Byline super-admin email',
        defaultValue: a.adminEmail ?? 'admin@byline.local',
      })
      ctx.state.patchAnswers({ adminEmail: email })
      values.secret.BYLINE_SUPERADMIN_EMAIL = email
    }

    if (missing.has('BYLINE_SUPERADMIN_PASSWORD')) {
      const pw = await ctx.prompter.password({
        message: 'Byline super-admin password (min 8 chars)',
        validate: (v) => (v.length < 8 ? 'must be at least 8 characters' : undefined),
      })
      values.secret.BYLINE_SUPERADMIN_PASSWORD = pw
    }

    if (missing.has('BYLINE_DB_POSTGRES_CONNECTION_STRING')) {
      const dbPassword = await resolveDbPassword(ctx)
      if (!dbPassword) return { state: 'blocked' }
      values.secret.BYLINE_DB_POSTGRES_CONNECTION_STRING = buildPgUrl({
        host: a.dbHost,
        port: a.dbPort ?? 5432,
        user: a.dbUser,
        password: dbPassword,
        database: a.dbName,
      })
    }

    for (const file of Object.keys(values) as EnvFile[]) {
      const path = ctx.resolve(ENV_FILE_PATHS[file])
      writeFileSync(path, renderEnvFile(values[file], file), 'utf8')
      ctx.logger.success(`wrote ${path}`)
    }
    return { state: 'done' }
  },
}

async function resolveDbPassword(ctx: Context): Promise<string | null> {
  if (ctx.secrets.dbPassword) return ctx.secrets.dbPassword
  const fromEnv = process.env.BYLINE_DB_PASSWORD
  if (fromEnv) {
    ctx.logger.info('using app role password from BYLINE_DB_PASSWORD')
    return fromEnv
  }
  const pw = await ctx.prompter.password({
    message:
      'Application database role password (re-enter to compose BYLINE_DB_POSTGRES_CONNECTION_STRING)',
  })
  if (!pw) {
    ctx.logger.error('password is required to compose BYLINE_DB_POSTGRES_CONNECTION_STRING')
    return null
  }
  ctx.secrets.dbPassword = pw
  return pw
}

function readAllEnvFiles(ctx: Context): Record<EnvFile, Record<string, string>> {
  const out: Record<EnvFile, Record<string, string>> = { public: {}, secret: {} }
  for (const file of Object.keys(ENV_FILE_PATHS) as EnvFile[]) {
    out[file] = readEnvFile(ctx.resolve(ENV_FILE_PATHS[file]))
  }
  return out
}

function readEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {}
  const out: Record<string, string> = {}
  const raw = readFileSync(path, 'utf8')
  for (const line of raw.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$/)
    if (!m) continue
    const key = m[1] as string
    let val = (m[2] ?? '').trim()
    if (val.startsWith('"') && val.endsWith('"')) {
      val = val.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\')
    } else if (val.startsWith("'") && val.endsWith("'")) {
      val = val.slice(1, -1)
    }
    out[key] = val
  }
  return out
}

function renderEnvFile(values: Record<string, string>, file: EnvFile): string {
  // Only emit specs belonging to this file; the other file owns the rest.
  const fileSpecs = ENV_SPECS.filter((s) => s.file === file)
  const known = new Set<string>(fileSpecs.map((s) => s.key))
  const groups: Record<'app' | 'database' | 'auth', string[]> = { app: [], database: [], auth: [] }
  for (const spec of fileSpecs) {
    const v = values[spec.key]
    if (v === undefined) continue
    groups[spec.group].push(`# ${spec.description}\n${spec.key}=${formatEnvValue(v)}`)
  }

  const sections: string[] = []
  sections.push(file === 'public' ? PUBLIC_FILE_HEADER : SECRET_FILE_HEADER)
  if (groups.app.length) sections.push(`# App\n${groups.app.join('\n\n')}`)
  if (groups.database.length) sections.push(`# Database\n${groups.database.join('\n\n')}`)
  if (groups.auth.length) sections.push(`# Auth\n${groups.auth.join('\n\n')}`)

  const extras = Object.entries(values)
    .filter(([k]) => !known.has(k))
    .map(([k, v]) => `${k}=${formatEnvValue(v)}`)
  if (extras.length) sections.push(`# Existing\n${extras.join('\n')}`)

  return `${sections.join('\n\n')}\n`
}

function formatEnvValue(v: string): string {
  if (v === '') return ''
  if (/^[A-Za-z0-9_\-./:@+]+$/.test(v)) return v
  return `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

// TanStack Start / Vite convention — see
// https://tanstack.com/start/latest/docs/framework/react/guide/environment-variables#environment-file-setup
// `.env` is committed; `.env.local` is gitignored and holds secrets.
const PUBLIC_FILE_HEADER = `# Public, non-secret defaults. Safe to commit to git.
# Secrets (DB URL, JWT signing key, admin credentials) live in .env.local.
# See https://tanstack.com/start/latest/docs/framework/react/guide/environment-variables#environment-file-setup`

const SECRET_FILE_HEADER = `# Local secrets — DO NOT commit. Gitignored by default.
# Public, non-secret defaults live in .env.
# See https://tanstack.com/start/latest/docs/framework/react/guide/environment-variables#environment-file-setup`
