/**
 * This Source Code is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) Infonomic Company Limited
 */

// import { z } from 'zod/v4'

import type { MaybePromise, NonEmptyArray } from './type-utils.js'

// ---------------------------------------------------------------------------
// Default values
// ---------------------------------------------------------------------------

// Fields can have default values, either statically defined, or generated by a
// function.  The function receives a context object with the current document
// data and locale, and can return a default value directly, or a promise that
// resolves to one.

/**
 * Context passed to functions that generate default values for fields,
 * containing the current document data, locale, and a few helper functions.
 */
export interface DefaultValueContext {
  /**
   * The current document data as it is being built/edited.  Defaults may read
   * other field values from here.
   */
  data: Record<string, any>

  /**
   * Current locale (when defaults are locale-aware).
   */
  locale?: string

  /**
   * Clock access for time-based defaults.
   */
  now: () => Date

  /**
   * UUID generator for defaults that need stable IDs.
   */
  uuid?: () => string
}

/**
 * A function that generates a default value for a field
 */
type DefaultValueFn<T> = (ctx: DefaultValueContext) => T | Promise<T>

/**
 * Either an actual default value, or a function that generates one
 */
export type DefaultValue<T = unknown> = T | DefaultValueFn<T>

// // Zod schema for validating the `defaultValue` property on field definitions.
// const defaultValueSchema = <T>(schema: z.ZodType<T>): z.ZodOptional<z.ZodType<DefaultValue<T>>> => {
//   return z
//     .union([schema, z.custom<DefaultValueFn<T>>((val) => typeof val === 'function')])
//     .optional()
// }

// ---------------------------------------------------------------------------
// Field-level hooks (client-side)
// ---------------------------------------------------------------------------

/**
 * Context passed to field-level hooks. Gives the hook access to the changing
 * value, the previous value, the full document data, and the field definition.
 */
export interface FieldHookContext {
  /**
   * The incoming value (after the user edit).
   */
  value: any

  /**
   *  The value before this edit.
   */
  previousValue: any

  /**
   * Current document data (full form state).
   */
  data: Record<string, any>

  /**
   * Dot-path of the field inside the document, e.g. `"content.0.richText"`.
   */
  path: string

  /**
   * The field definition this hook is attached to.
   */
  field: Field

  /**
   * `'change'` — fired on every keystroke / field edit.
   * `'submit'` — fired once during form submit, before `validateForm()`.
   *
   * Hooks can use this to vary behaviour, e.g. only auto-populate a
   * derived value at submit time while showing advisory errors on change.
   */
  operation: 'change' | 'submit'
}

/**
 * Return type of `beforeValidate` hooks.
 */
export interface FieldBeforeValidateResult {
  /** If set, the change is blocked and this message is shown as a field error. */
  error?: string
}

/**
 * A single `beforeValidate` hook function
 */
export type FieldBeforeValidateFn = (
  ctx: FieldHookContext
) => MaybePromise<FieldBeforeValidateResult | void>

/**
 * Return type of `beforeChange`. Allows the hook to:
 *  - replace the value (`value`),
 *  - reject the change with a per-field error (`error`),
 *  - or do nothing (return `undefined` / `{}`).
 */
export interface FieldBeforeChangeResult {
  /** If set, this value replaces the incoming value. */
  value?: any
  /** If set, the change is blocked and this message is shown as a field error. */
  error?: string
}

/**
 * A single beforeChange hook function.
 */
export type FieldBeforeChangeFn = (
  ctx: FieldHookContext
) => MaybePromise<FieldBeforeChangeResult | void>

/**
 * Hooks that can be attached to any field via the `hooks` property on the
 * field definition. Both hooks are async-capable to support debounced
 * remote validation or similar patterns.
 *
 * Each hook accepts a single function or an **array** of functions that
 * are executed in order. Execution stops at the first function that
 * returns `{ error }` (for blocking hooks like `beforeChange`).
 */
export interface FieldHooks {
  /**
   * Fires **before** the built-in validation rules are evaluated.
   *
   * This hook is **advisory**: the value is always committed to the form
   * store regardless of the result. Returning `{ error }` displays a
   * per-field error (useful for live validation feedback) but does **not**
   * block the change — the user can keep typing.
   */
  beforeValidate?: FieldBeforeValidateFn | FieldBeforeValidateFn[]

  /**
   * Fires **after** `beforeValidate` but **before** the value is committed
   * to the form store and a patch is emitted.
   *
   * Returning `{ value }` substitutes the committed value (e.g. trim, slug).
   * Returning `{ error }` **blocks** the change — the value is not written.
   *
   * ⚠️  Value transformations will reset the cursor position in text inputs.
   * Prefer `beforeValidate` for feedback that should not interfere with typing.
   */
  beforeChange?: FieldBeforeChangeFn | FieldBeforeChangeFn[]
}

/**
 * Normalise a hook slot (single function or array) into a flat array.
 */
export function normalizeHooks<T>(hook: T | T[] | undefined): T[] {
  if (!hook) return []
  return Array.isArray(hook) ? hook : [hook]
}

// // Schemas for validating field hooks at runtime (e.g. in `defineCollection()`)
// const fieldBeforeValidateFnSchema = z.custom<FieldBeforeValidateFn>(
//   (val) => typeof val === 'function'
// )
// const fieldBeforeChangeFnSchema = z.custom<FieldBeforeChangeFn>((val) => typeof val === 'function')
// const fieldHooksSchema = z.object({
//   beforeValidate: z
//     .union([fieldBeforeValidateFnSchema, z.array(fieldBeforeValidateFnSchema)])
//     .optional(),
//   beforeChange: z.union([fieldBeforeChangeFnSchema, z.array(fieldBeforeChangeFnSchema)]).optional(),
// })

// ---------------------------------------------------------------------------
// Field validation types
// ---------------------------------------------------------------------------

export interface ValidationRule {
  type: 'min' | 'max' | 'pattern' | 'custom' | 'email' | 'url'
  value: any
  message?: string
}

// See the comment for BaseField.validate
type FieldValidateFn = (value: any, data: Record<string, any>) => string | undefined

// const fieldValidateFnSchema = z.custom<FieldValidateFn>((val) => typeof val === 'function')

// ---------------------------------------------------------------------------
// Base (common) properties for field definitions
// ---------------------------------------------------------------------------

/**
 * Base properties shared by all fields
 */
interface BaseField {
  name: string
  label?: string
  helpText?: string
  placeholder?: string // TODO: Move this to fields that actually support it

  // unique?: boolean

  /**
   * Is this field optional or required?  Fields are required by default; set
   * this to `true` to make the field optional.  If the field is required, a
   * value must be provided (possibly via a default value or hook) for the
   * document to be considered valid.
   */
  optional?: boolean

  /**
   * Optional field-level hooks that run on the client during editing.
   * @see FieldHooks
   */
  hooks?: FieldHooks

  /**
   * Optional submit-time validator. Called by `validateForm()` for every field
   * type — including structure fields (group, array, blocks).
   *
   * Receives the resolved field value (lodash `get` on the full form store, so
   * group fields arrive as their assembled value, e.g. `[{en:true},{fr:false}]`)
   * and the complete form data snapshot.
   *
   * Return a non-empty string to block submission and display the message as a
   * field-level error. Return `undefined` (or nothing) to pass.
   */
  validate?: FieldValidateFn
}

/**
 * Base for fields that support localization (i.e. may be configured to have
 * separate values per locale).
 */
interface LocalizableField extends BaseField {
  localized?: boolean
}

/**
 * Base for fields that do not support localization (i.e. always have a single
 * value across all locales).
 */
interface NonlocalizableField extends BaseField {
  localized?: false
}

// const baseFieldSchema = z.object({
//   name: z.string(),
//   label: z.string().optional(),
//   helpText: z.string().optional(),
//   placeholder: z.string().optional(),
//   required: z.boolean().optional(),
//   hooks: fieldHooksSchema.optional(),
//   validate: fieldValidateFnSchema,
// }) satisfies z.ZodType<BaseField>

// const localizableFieldSchema = z.object({
//   ...baseFieldSchema.shape,
//   localized: z.boolean().optional(),
// }) satisfies z.ZodType<LocalizableField>

// ---------------------------------------------------------------------------
// Group field
// ---------------------------------------------------------------------------

export interface GroupField extends NonlocalizableField {
  type: 'group'
  fields: FieldSet
}

// ---------------------------------------------------------------------------
// Array field
// ---------------------------------------------------------------------------

export interface ArrayField extends NonlocalizableField {
  type: 'array'
  fields: FieldSet
  validation?: {
    minLength?: number
    maxLength?: number
  }
}

// ---------------------------------------------------------------------------
// Blocks field
// ---------------------------------------------------------------------------

export interface Block {
  blockType: string
  fields: FieldSet

  label?: string
  helpText?: string
  hooks?: FieldHooks
  validate?: FieldValidateFn
}

export interface BlocksField extends NonlocalizableField {
  type: 'blocks'
  blocks: Block[]
}

// ---------------------------------------------------------------------------
// Text field
// ---------------------------------------------------------------------------

export interface TextField extends LocalizableField {
  type: 'text'
  defaultValue?: DefaultValue<string>
  validation?: {
    minLength?: number
    maxLength?: number
    pattern?: string
    rules?: ValidationRule[]
  }
}

// ---------------------------------------------------------------------------
// TextArea field
// ---------------------------------------------------------------------------

export interface TextAreaField extends LocalizableField {
  type: 'textArea'
  defaultValue?: DefaultValue<string>
  validation?: {
    minLength?: number
    maxLength?: number
    pattern?: string
    rules?: ValidationRule[]
  }
}

// ---------------------------------------------------------------------------
// Checkbox field
// ---------------------------------------------------------------------------

// TODO: Should this be localizable?
export interface CheckboxField extends NonlocalizableField {
  type: 'checkbox'
  defaultValue?: DefaultValue<boolean>
}

// ---------------------------------------------------------------------------
// Boolean field
// ---------------------------------------------------------------------------

// TODO: Should this be localizable?
export interface BooleanField extends NonlocalizableField {
  type: 'boolean'
  defaultValue?: DefaultValue<boolean>
}

// ---------------------------------------------------------------------------
// Select field
// ---------------------------------------------------------------------------

export interface SelectFieldOption {
  label: string
  value: string
}

// TODO: Should this be localizable?
export interface SelectField<
  Options extends NonEmptyArray<SelectFieldOption> = NonEmptyArray<SelectFieldOption>,
> extends NonlocalizableField {
  type: 'select'
  options: Options
  defaultValue?: DefaultValue<Options[number]['value']>
}

// ---------------------------------------------------------------------------
// RichText field
// ---------------------------------------------------------------------------

export interface RichTextField extends LocalizableField {
  type: 'richText'
  defaultValue?: DefaultValue<unknown>
  validation?: {
    minLength?: number
    maxLength?: number
  }
  /**
   * Editor-specific configuration. The shape is opaque to `@byline/core` —
   * each editor adapter defines what it accepts. For `@byline/richtext-lexical`
   * this is its `EditorConfig`. Per-field config takes precedence over any
   * baked-in config supplied at registration via `lexicalEditor()`.
   */
  editorConfig?: unknown
}

// ---------------------------------------------------------------------------
// Time field
// ---------------------------------------------------------------------------

export interface TimeField extends NonlocalizableField {
  type: 'time'
  defaultValue?: DefaultValue<'00:00' | string> // Default to midnight
}

// ---------------------------------------------------------------------------
// Date field
// ---------------------------------------------------------------------------

export interface DateField extends NonlocalizableField {
  type: 'date'
  defaultValue?: DefaultValue<Date>
}

// ---------------------------------------------------------------------------
// DateTime field
// ---------------------------------------------------------------------------

export interface DateTimeField extends NonlocalizableField {
  type: 'datetime'
  mode?: 'date' | 'datetime'
  // dateOnly?: boolean // if true, only the date part is stored
  yearsInFuture?: number
  yearsInPast?: number
  defaultValue?: DefaultValue<Date>
}

// ---------------------------------------------------------------------------
// Float field
// ---------------------------------------------------------------------------

export interface FloatField extends NonlocalizableField {
  type: 'float'
  defaultValue?: DefaultValue<number>
  validation?: {
    min?: number
    max?: number
  }
}

// ---------------------------------------------------------------------------
// Integer field
// ---------------------------------------------------------------------------

export interface IntegerField extends NonlocalizableField {
  type: 'integer'
  defaultValue?: DefaultValue<number>
  validation?: {
    min?: number
    max?: number
  }
}

// ---------------------------------------------------------------------------
// Decimal field
// ---------------------------------------------------------------------------

export interface DecimalField extends NonlocalizableField {
  type: 'decimal'
  defaultValue?: DefaultValue<string>
}

// ---------------------------------------------------------------------------
// Json field
// ---------------------------------------------------------------------------

export interface JsonField extends LocalizableField {
  type: 'json'
  defaultValue?: DefaultValue<unknown>
}

// ---------------------------------------------------------------------------
// Object field
// ---------------------------------------------------------------------------

export interface ObjectField extends LocalizableField {
  type: 'object'
  defaultValue?: DefaultValue<Record<string, any>>
}

// ---------------------------------------------------------------------------
// Relation field
// ---------------------------------------------------------------------------

export interface RelationField extends NonlocalizableField {
  type: 'relation'

  /**
   * The `path` of the target collection (e.g. `'media'` or `'authors'`). The
   * field picker will query this collection when selecting a reference.
   */
  targetCollection: string

  /**
   * Field name from the target collection to display in the picker and inline
   * summary. Falls back to the first text field if omitted.
   */
  displayField?: string
}

// ---------------------------------------------------------------------------
// File field
// ---------------------------------------------------------------------------

export interface FileField extends NonlocalizableField {
  type: 'file'
  // TODO: Validation rules, e.g. allowed formats, file size etc.
}

// ---------------------------------------------------------------------------
// Image field
// ---------------------------------------------------------------------------

export interface ImageField extends NonlocalizableField {
  type: 'image'
  // TODO: Validation rules, e.g. allowed formats, file size, aspect ratios etc.
}

// ---------------------------------------------------------------------------
// Combined field types
// ---------------------------------------------------------------------------

export type StructureField = GroupField | ArrayField | BlocksField

export type ValueField =
  | TextField
  | TextAreaField
  | CheckboxField
  | BooleanField
  | SelectField
  | RichTextField
  | TimeField
  | DateField
  | DateTimeField
  | FloatField
  | IntegerField
  | DecimalField
  | JsonField
  | ObjectField
  | RelationField
  | FileField
  | ImageField

export type Field = StructureField | ValueField

export type FieldSet = readonly Field[]

export type ValueFieldType = ValueField['type']
export type StructureFieldType = StructureField['type']
export type FieldType = Field['type']

export type LocalizedField = { localized: true }
export type OptionalField = { optional: true }

// Type guards for field identification
export function isStructureField(field: Field): field is StructureField {
  return ['array', 'blocks', 'group'].includes(field.type)
}

export function isArrayField(field: Field): field is ArrayField {
  return field.type === 'array'
}

export function isBlocksField(field: Field): field is BlocksField {
  return field.type === 'blocks'
}

export function isGroupField(field: Field): field is GroupField {
  return field.type === 'group'
}

export function isValueField(field: Field): field is ValueField {
  return !isStructureField(field)
}

// ---------------------------------------------------------------------------
// Component slots for value fields (UI extensibility)
// ---------------------------------------------------------------------------

// TODO: Move this to a separate file.

/**
 * A framework-agnostic component type. In practice will be a React
 * `ComponentType<P>`, but defined here without importing React so that
 * `@byline/core` stays server-safe.
 */
export type SlotComponent<P = Record<string, unknown>> = (props: P) => any

/**
 * Base props passed to every custom slot component.
 * Slot components also have access to form context via hooks
 * (`useFieldValue`, `useFieldError`, `useFormContext`, etc.) since
 * they render inside the `FormProvider`.
 */
export interface FieldSlotBaseProps {
  /** The field definition this slot belongs to. */
  field: Field
  /** Dot-path of the field in the document, e.g. `"content.0.richText"`. */
  path: string
  /** Current field value (snapshot at render time). */
  value: any
  /** Current field error message, if any. */
  error?: string
  /** HTML `id` for the field element (useful for `htmlFor`). */
  id: string
}

/**
 * Props passed to a custom **Label** slot component.
 *
 * @example
 * ```tsx
 * const MyLabel: SlotComponent<FieldLabelSlotProps> = ({ label, required }) => (
 *   <span>{label}{required && ' *'}</span>
 * )
 * ```
 */
export interface FieldLabelSlotProps extends FieldSlotBaseProps {
  /** The label string from the field definition. */
  label?: string
  /** Whether the field is required. */
  required?: boolean
}

/**
 * Props passed to a custom **HelpText** slot component.
 */
export interface FieldHelpTextSlotProps extends FieldSlotBaseProps {
  /** The help-text string from the field definition. */
  helpText?: string
}

/**
 * Props passed to a custom **Field** (input replacement) slot component.
 *
 * When a `Field` slot is provided it **completely replaces** the default
 * input widget. The component must call `onChange` to commit value changes
 * back to the form store.
 */
export interface FieldInputSlotProps extends FieldSlotBaseProps {
  /** Call this to write a new value to the form store (runs the hook pipeline). */
  onChange: (value: any) => void
  /** Default value for the field. */
  defaultValue?: any
  /** Placeholder text from the field definition. */
  placeholder?: string
}

/**
 * Props passed to **beforeField** / **afterField** adornment slot components.
 */
export interface FieldAdornmentSlotProps extends FieldSlotBaseProps {}

/**
 * Optional UI component overrides that can be attached to any **value field**.
 *
 * Each slot receives typed props (see individual `*SlotProps` interfaces) and
 * can also use form-context hooks for reactive data.
 *
 * @example
 * ```ts
 * {
 *   name: 'title',
 *   type: 'text',
 *   label: 'Title',
 *   components: {
 *     Label: ({ label }) => <h3>{label}</h3>,
 *     afterField: ({ value }) => (
 *       <p className="text-xs text-gray-400">{value?.length ?? 0} chars</p>
 *     ),
 *   },
 * }
 * ```
 */
export interface FieldComponentSlots {
  /**
   * Replaces the default label. Receives `FieldLabelSlotProps`.
   * When provided, the built-in `<Label>` is **not** rendered.
   */
  Label?: SlotComponent<FieldLabelSlotProps>
  /**
   * Replaces the default help text. Receives `FieldHelpTextSlotProps`.
   * When provided, the built-in help-text string is **not** rendered.
   */
  HelpText?: SlotComponent<FieldHelpTextSlotProps>
  /**
   * Completely replaces the default field input. Receives `FieldInputSlotProps`.
   * When provided the default `<Input>` (or equivalent) is **not** rendered.
   */
  Field?: SlotComponent<FieldInputSlotProps>
  /**
   * Rendered **before** the field input (between the label and the input).
   * Receives `FieldAdornmentSlotProps`.
   */
  beforeField?: SlotComponent<FieldAdornmentSlotProps>
  /**
   * Rendered **after** the field input (between the input and any help text).
   * Receives `FieldAdornmentSlotProps`.
   */
  afterField?: SlotComponent<FieldAdornmentSlotProps>
}

// ---------------------------------------------------------------------------
// Richtext editor adapter contract
// ---------------------------------------------------------------------------

/**
 * Props passed to a configured richtext editor component. Mirrors the
 * arguments the field-renderer already supplies for `type: 'richText'`
 * fields, so an adapter package can satisfy the contract by re-exporting
 * a thin wrapper around its underlying editor.
 *
 * Editor packages (e.g. `@byline/richtext-lexical`) expose a component
 * matching this shape, and the installation registers it as the
 * site-wide default via `ClientConfig.fields.richText.editor`.
 */
export interface RichTextEditorProps {
  /** The field definition (label / helpText / optional / hooks / validate). */
  field: RichTextField
  /** Initial value to seed the editor with on first render. */
  defaultValue?: unknown
  /** Commit a new value to the form store (runs the field hook pipeline). */
  onChange: (value: unknown) => void
  /** Dot-path of the field in the document, e.g. `"content.0.body"`. */
  path: string
  /** Stable identity for editor instances; used as a React `key`. */
  instanceKey: string
  /** Active content locale; the editor may render a locale badge if set. */
  locale?: string
}

/**
 * Component shape an editor package must export to be plugged in via
 * `ClientConfig.fields.richText.editor`. Built on `SlotComponent` so the
 * type stays React-agnostic at the `@byline/core` boundary.
 */
export type RichTextEditorComponent = SlotComponent<RichTextEditorProps>
