-- @byline/analytics-postgres — 0001_init
--
-- Driver-owned raw events, daily salts, bounded daily aggregates, and rollup
-- cursor. The migration runner records this file in
-- byline_analytics_migrations; these tables are independent of the host
-- application's Drizzle migration stream.

CREATE TABLE IF NOT EXISTS byline_analytics_event (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at    timestamptz NOT NULL,
  kind           text        NOT NULL CHECK (kind IN ('page', 'download')),
  source         text        NOT NULL CHECK (source IN ('beacon', 'redirect', 'cdnlog')),
  path           text        NOT NULL CHECK (char_length(path) <= 512 AND path <> '__other__'),
  visitor_hash   char(64)    NOT NULL CHECK (visitor_hash ~ '^[0-9a-f]{64}$'),
  referrer_host  text        CHECK (
    referrer_host IS NULL OR
    (char_length(referrer_host) <= 255 AND referrer_host <> '__other__')
  ),
  country        char(2)     CHECK (country IS NULL OR country ~ '^[A-Z]{2}$')
);

CREATE INDEX IF NOT EXISTS byline_analytics_event_occurred_at_idx
  ON byline_analytics_event (occurred_at);

CREATE TABLE IF NOT EXISTS byline_analytics_salt (
  day   date  PRIMARY KEY,
  salt  bytea NOT NULL CHECK (octet_length(salt) = 32)
);

CREATE TABLE IF NOT EXISTS byline_analytics_daily_path (
  day       date     NOT NULL,
  kind      text     NOT NULL CHECK (kind IN ('page', 'download')),
  path      text     NOT NULL,
  views     bigint   NOT NULL CHECK (views >= 0),
  visitors  bigint   NOT NULL CHECK (visitors >= 0),
  PRIMARY KEY (day, kind, path)
);

CREATE INDEX IF NOT EXISTS byline_analytics_daily_path_day_idx
  ON byline_analytics_daily_path (day);

CREATE TABLE IF NOT EXISTS byline_analytics_daily_site (
  day        date    PRIMARY KEY,
  views      bigint  NOT NULL CHECK (views >= 0),
  visitors   bigint  NOT NULL CHECK (visitors >= 0),
  downloads  bigint  NOT NULL CHECK (downloads >= 0)
);

CREATE TABLE IF NOT EXISTS byline_analytics_daily_referrer (
  day            date    NOT NULL,
  referrer_host  text    NOT NULL,
  views          bigint  NOT NULL CHECK (views >= 0),
  visitors       bigint  NOT NULL CHECK (visitors >= 0),
  PRIMARY KEY (day, referrer_host)
);

CREATE INDEX IF NOT EXISTS byline_analytics_daily_referrer_day_idx
  ON byline_analytics_daily_referrer (day);

CREATE TABLE IF NOT EXISTS byline_analytics_daily_country (
  day       date     NOT NULL,
  country   char(2)  NOT NULL,
  views     bigint   NOT NULL CHECK (views >= 0),
  visitors  bigint   NOT NULL CHECK (visitors >= 0),
  PRIMARY KEY (day, country)
);

CREATE TABLE IF NOT EXISTS byline_analytics_rollup_state (
  singleton          smallint PRIMARY KEY DEFAULT 1 CHECK (singleton = 1),
  last_complete_day  date
);
