import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, expectTypeOf, it } from 'vitest'

import {
  AllFieldsCollection,
  AllFieldsCollections,
  type MediaBlock as MediaBlockDefinition,
  type QuoteBlock,
} from './fixtures/all-fields.js'
import { emitCollectionTypes } from './index.js'
import type {
  CollectionDefinition,
  CollectionFieldData,
  CollectionFieldDataAllLocales,
} from '../@types/collection-types.js'
import type {
  AllFieldsFields,
  AllFieldsFieldsAllLocales,
  CollectionFieldsAllLocalesByPath,
  CollectionFieldsByPath,
  CollectionPath,
  MediaBlockData,
  MediaBlockDataAllLocales,
  QuoteBlockData,
  QuoteBlockDataAllLocales,
} from './fixtures/all-fields.expected.js'

const fixtureDirectory = resolve(dirname(fileURLToPath(import.meta.url)), 'fixtures')

function collection(path: string, fields: CollectionDefinition['fields']): CollectionDefinition {
  return { path, labels: { singular: path, plural: path }, fields }
}

describe('emitCollectionTypes', () => {
  it('matches the checked-in all-fields fixture and canonical inferred contracts exactly', () => {
    const result = emitCollectionTypes(AllFieldsCollections)
    const fixture = readFileSync(resolve(fixtureDirectory, 'all-fields.generated.txt'), 'utf8')

    expect(result.source).toBe(fixture)
    expectTypeOf<AllFieldsFields>().toEqualTypeOf<CollectionFieldData<typeof AllFieldsCollection>>()
    expectTypeOf<AllFieldsFieldsAllLocales>().toEqualTypeOf<
      CollectionFieldDataAllLocales<typeof AllFieldsCollection>
    >()
    expectTypeOf<MediaBlockData>().toEqualTypeOf<{
      _id: string
      _type: 'media'
      caption?: string | undefined
      image: import('../@types/field-data-types.js').StoredFileValue
    }>()
    expectTypeOf<MediaBlockDataAllLocales>().toEqualTypeOf<{
      _id: string
      _type: 'media'
      caption?: Record<string, string> | undefined
      image: import('../@types/field-data-types.js').StoredFileValue
    }>()
    expectTypeOf<QuoteBlockData>().toEqualTypeOf<
      import('../@types/collection-types.js').BlockData<typeof QuoteBlock>
    >()
    expectTypeOf<QuoteBlockDataAllLocales>().toEqualTypeOf<{
      _id: string
      _type: "quote'block"
      quotation: Record<string, string>
      "tone'choice"?: 'calm' | "author's" | undefined
      snippet?: string | undefined
    }>()
    expectTypeOf<CollectionFieldsByPath['all-fields']>().toEqualTypeOf<AllFieldsFields>()
    expectTypeOf<
      CollectionFieldsAllLocalesByPath['all-fields']
    >().toEqualTypeOf<AllFieldsFieldsAllLocales>()
    expectTypeOf<CollectionPath>().toEqualTypeOf<'all-fields' | 'minimal'>()
    expectTypeOf<typeof MediaBlockDefinition.blockType>().toEqualTypeOf<'media'>()
  })

  it('emits a versioned header, verifiable body hash, and canonical formatting', () => {
    const { source, hash } = emitCollectionTypes([collection('plain', [])])
    const body = source.split('\n').slice(4).join('\n')

    expect(source).toMatch(
      /^\/\/ Generated by @byline\/core\/codegen\n\/\/ Format version: 2\n\/\/ Hash: [a-f0-9]{64}\n\n/
    )
    expect(hash).toBe(
      createHash('sha256').update(`@byline/core/codegen:collection-types:v2\n${body}`).digest('hex')
    )
    expect(source).toContain(`// Hash: ${hash}`)
    expect(source.endsWith('\n')).toBe(true)
    expect(source).not.toContain('\r')
    expect(source).not.toContain(';')
  })

  it('declares every type inside the @byline/generated-types augmentation block', () => {
    const { source } = emitCollectionTypes([collection('plain', [{ name: 'title', type: 'text' }])])
    expect(source).toContain("declare module '@byline/generated-types' {")
    expect(source).toContain('  export type PlainFields = {')
    expect(source).toContain('  export type CollectionPath = keyof CollectionFieldsByPath')
    // No module-level type exports outside the augmentation blocks.
    expect(source).not.toMatch(/^export /m)
  })

  it('emits the @byline/client Register augmentation referencing the generated registry', () => {
    const { source } = emitCollectionTypes([collection('plain', [])])
    expect(source).toContain(
      [
        "declare module '@byline/client' {",
        '  interface Register {',
        "    collections: import('@byline/generated-types').CollectionFieldsByPath",
        '  }',
        '}',
      ].join('\n')
    )
  })

  it('sorts collections and declarations without changing field, select, or block union order', () => {
    const alpha = collection('alpha', [
      {
        name: 'choice',
        type: 'select',
        options: [
          { label: 'Zulu', value: 'zulu' },
          { label: 'Duplicate Zulu', value: 'zulu' },
          { label: 'Alpha', value: 'alpha' },
        ],
      },
      {
        name: 'content',
        type: 'blocks',
        blocks: [
          { blockType: 'zulu', fields: [] },
          { blockType: 'alpha', fields: [] },
        ],
      },
    ])
    const zulu = collection('zulu', [{ name: 'title', type: 'text' }])
    const forward = emitCollectionTypes([zulu, alpha])
    const reverse = emitCollectionTypes([alpha, zulu])

    expect(forward).toEqual(reverse)
    expect(forward.source).toContain(`choice: 'zulu' | 'alpha'`)
    expect(forward.source).toContain(`content: Array<ZuluBlockData | AlphaBlockData>`)
    expect(forward.source.indexOf(`alpha: AlphaFields`)).toBeLessThan(
      forward.source.indexOf(`zulu: ZuluFields`)
    )
  })

  it('normalizes identifiers and quotes only invalid property keys', () => {
    const source = emitCollectionTypes([
      collection('API_response', [
        { name: 'validKey', type: 'text' },
        { name: 'café', type: 'text' },
        { name: 'not-valid', type: 'text' },
        {
          name: 'choice',
          type: 'select',
          options: [
            { label: 'First', value: 'first' },
            { label: 'First duplicate', value: 'first' },
            { label: 'Second', value: 'second' },
          ],
        },
        {
          name: 'content',
          type: 'blocks',
          blocks: [{ blockType: 'photoBlock', fields: [] }],
        },
      ]),
      collection('photoBlock', []),
      collection('café—API_response', []),
    ]).source

    expect(source).toContain('export type ApiResponseFields = {')
    expect(source).toContain('export type PhotoBlockFields = {}')
    expect(source).toContain('export type CafeApiResponseFields = {}')
    expect(source).toContain('export type PhotoBlockData = {')
    expect(source).toContain('validKey: string')
    expect(source).toContain('café: string')
    expect(source).toContain(`'not-valid': string`)
    expect(source).toContain(`choice: 'first' | 'second'`)
    expect(source).toContain('API_response: ApiResponseFields')
    expect(source).toContain(`'café—API_response': CafeApiResponseFields`)
  })

  it('ignores non-type metadata but changes output for type-significant values', () => {
    const base = collection('articles', [
      { name: 'title', type: 'text' },
      { name: 'kind', type: 'select', options: [{ label: 'News', value: 'news' }] },
    ])
    const metadataOnly: CollectionDefinition = {
      ...base,
      labels: { singular: 'Story', plural: 'Stories' },
      version: 99,
      fields: [
        { name: 'title', type: 'text', label: 'Headline', helpText: 'Displayed prominently' },
        {
          name: 'kind',
          type: 'select',
          label: 'Kind',
          options: [{ label: 'Article', value: 'news' }],
        },
      ],
    }
    const changed = collection('articles', [
      { name: 'title', type: 'integer' },
      { name: 'kind', type: 'select', options: [{ label: 'News', value: 'report' }] },
    ])

    expect(emitCollectionTypes([metadataOnly])).toEqual(emitCollectionTypes([base]))
    expect(emitCollectionTypes([changed]).hash).not.toBe(emitCollectionTypes([base]).hash)
  })

  it('imports only used canonical types in fixed order', () => {
    const noImports = emitCollectionTypes([
      collection('simple', [{ name: 'title', type: 'text' }]),
    ]).source
    const selectedImports = emitCollectionTypes([
      collection('typed', [
        { name: 'data', type: 'json' },
        { name: 'relation', type: 'relation', targetCollection: 'simple' },
        { name: 'file', type: 'file' },
      ]),
    ]).source

    expect(noImports).not.toContain('import type')
    expect(selectedImports).toContain(
      "import type {\n  JsonValue,\n  RelatedDocumentValue,\n  StoredFileValue,\n} from '@byline/core'"
    )
    expect(selectedImports).not.toContain('JsonObject')
  })

  it('reuses identical block contracts and suffixes incompatible normalized names', () => {
    const sharedA = { blockType: 'hero', fields: [{ name: 'title', type: 'text' }] } as const
    const sharedB = {
      blockType: 'hero',
      fields: [{ name: 'title', type: 'text', label: 'Ignored metadata' }],
    } as const
    const incompatible = {
      blockType: 'hero',
      fields: [{ name: 'title', type: 'integer' }],
    } as const
    const source = emitCollectionTypes([
      collection('foo-bar', [{ name: 'content', type: 'blocks', blocks: [sharedA] }]),
      collection('foo_bar', [{ name: 'content', type: 'blocks', blocks: [sharedB] }]),
      collection('other', [{ name: 'content', type: 'blocks', blocks: [incompatible] }]),
    ]).source

    expect(source.match(/export type HeroBlockData_[a-f0-9]+ =/g)).toHaveLength(2)
    expect(source.match(/export type FooBarFields_[a-f0-9]+ =/g)).toHaveLength(2)
    expect(source.match(/_type: 'hero'/g)).toHaveLength(4)
  })

  it('escapes property keys, block discriminants, and select literals', () => {
    const source = emitCollectionTypes([AllFieldsCollection]).source

    expect(source).toContain(`'content\\'s':`)
    expect(source).toContain(`_type: 'quote\\'block'`)
    expect(source).toContain(`'tone\\'choice'?: 'calm' | 'author\\'s' | undefined`)
  })

  it('does not mutate definitions and accepts deeply frozen input', () => {
    const field = Object.freeze({ name: 'title', type: 'text' } as const)
    const fields = Object.freeze([field])
    const definition = Object.freeze({
      path: 'frozen',
      labels: Object.freeze({ singular: 'Frozen', plural: 'Frozen' }),
      fields,
    })
    const before = JSON.stringify(definition)

    emitCollectionTypes(Object.freeze([definition]) as unknown as readonly CollectionDefinition[])
    expect(JSON.stringify(definition)).toBe(before)
  })

  it('rejects duplicate collection paths', () => {
    expect(() => emitCollectionTypes([collection('same', []), collection('same', [])])).toThrow(
      "duplicate collection path 'same'"
    )
  })

  it('rejects duplicate sibling fields at any nesting level', () => {
    expect(() =>
      emitCollectionTypes([
        collection('duplicates', [
          {
            name: 'group',
            type: 'group',
            fields: [
              { name: 'same', type: 'text' },
              { name: 'same', type: 'integer' },
            ],
          },
        ]),
      ])
    ).toThrow("duplicate sibling field 'same'")
  })

  it('rejects duplicate block types within one blocks field', () => {
    expect(() =>
      emitCollectionTypes([
        collection('duplicates', [
          {
            name: 'content',
            type: 'blocks',
            blocks: [
              { blockType: 'hero', fields: [] },
              { blockType: 'hero', fields: [{ name: 'title', type: 'text' }] },
            ],
          },
        ]),
      ])
    ).toThrow("duplicate local block type 'hero'")
  })

  it('rejects cyclic runtime definitions', () => {
    const fields: CollectionDefinition['fields'] = []
    fields.push({ name: 'recursive', type: 'group', fields })

    expect(() => emitCollectionTypes([collection('cycle', fields)])).toThrow('cycle detected')
  })

  it('rejects unsupported runtime field types', () => {
    expect(() =>
      emitCollectionTypes([
        collection('unsupported', [{ name: 'future', type: 'future' } as never]),
      ])
    ).toThrow("unsupported runtime field type 'future'")
  })

  it('is exposed only through the published codegen subpath', () => {
    const packageJson = JSON.parse(
      readFileSync(resolve(fixtureDirectory, '../../../package.json'), 'utf8')
    ) as { exports: Record<string, unknown> }
    const rootSource = readFileSync(resolve(fixtureDirectory, '../../index.ts'), 'utf8')

    expect(packageJson.exports['./codegen']).toEqual({
      types: './dist/codegen/index.d.ts',
      import: './dist/codegen/index.js',
      require: './dist/codegen/index.js',
    })
    expect(rootSource).not.toMatch(/codegen/)
  })
})
