/**
 * This Source Code is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) Infonomic Company Limited
 */

import type { ImageSize, StoredFileValue } from '@byline/core'

import type { Position } from '../../nodes/inline-image-node/types'

/**
 * Maps an editor `position` choice to a media-collection variant name.
 * Floated images (`left`/`right`) sit in narrow columns alongside text, so
 * they get the smaller `card` variant. `full` images use the main column,
 * `wide` ones bleed beyond it. Sizes refer to the variants declared on the
 * `media` collection in `apps/webapp/byline/collections/media/schema.ts`.
 */
function variantFor(position: Position): string {
  switch (position) {
    case 'left':
    case 'right':
      return 'card'
    case 'wide':
      return 'desktop'
    default:
      // 'full' | 'default' | undefined
      return 'tablet'
  }
}

/**
 * Derive a variant URL by suffix-swap on the original `storage_url`. Sharp
 * writes variants as siblings using the convention
 * `<basename>-<variantName>.<outputExt>`, e.g.
 *   `/uploads/media/abc-photo.jpg` → `/uploads/media/abc-photo-card.webp`
 *
 * Same convention as `media-thumbnail.tsx` — keep them in lock-step.
 */
function deriveVariantUrl(storageUrl: string, variant: string): string {
  return storageUrl.replace(/\.[^.]+$/, `-${variant}.webp`)
}

export interface PreferredSize {
  url: string
  width?: number
  height?: number
}

/**
 * Choose a sensible image URL + dimensions for the editor preview given the
 * picked media's `image` field and the user's chosen position. SVGs return
 * the original `storage_url` (no variants generated). Falls back gracefully
 * if no variants exist or the image is missing.
 */
export function getPreferredSize(
  position: Position,
  image: StoredFileValue | null | undefined
): PreferredSize | null {
  if (image?.storage_url == null) return null

  // SVGs aren't resized — original URL only.
  if (image.mime_type === 'image/svg+xml') {
    return {
      url: image.storage_url,
      width: image.image_width,
      height: image.image_height,
    }
  }

  const variant = variantFor(position)
  return {
    url: deriveVariantUrl(image.storage_url, variant),
    // We don't have per-variant dimensions in StoredFileValue (variants are
    // generated by Sharp but their dimensions aren't stored back). Hand the
    // original dimensions through; the renderer can constrain via CSS.
    width: image.image_width,
    height: image.image_height,
  }
}

/**
 * One denormalised image variant. `width` / `height` are the *declared*
 * targets from the collection's `upload.sizes` config — Sharp's actual
 * output may differ depending on `fit`, but the declared values are stable
 * upper bounds the renderer can use for `<img width>` / responsive layout.
 */
export interface DerivedImageSize {
  name: string
  url: string
  width?: number
  height?: number
  format: string
}

/**
 * Derive the full set of variant URLs for a picked image, given the source
 * collection's `upload.sizes` config. Each variant URL is computed by
 * suffix-swap on the original `storage_url` — Sharp writes variants as
 * siblings using `<basename>-<variantName>.<outputFormat>` (defaults to
 * webp when `format` is omitted in the schema, matching the image-processor
 * default).
 *
 * SVGs and missing storage URLs return `[]` — Sharp doesn't process either,
 * so renderers should fall back to `image.storage_url`.
 */
export function deriveImageSizes(
  image: StoredFileValue | null | undefined,
  sizesConfig: ImageSize[] | undefined
): DerivedImageSize[] {
  if (!image?.storage_url) return []
  if (image.mime_type === 'image/svg+xml') return []
  if (!sizesConfig || sizesConfig.length === 0) return []

  const storageUrl = image.storage_url
  return sizesConfig.map((size) => {
    const format = size.format ?? 'webp'
    return {
      name: size.name,
      url: storageUrl.replace(/\.[^.]+$/, `-${size.name}.${format}`),
      width: size.width,
      height: size.height,
      format,
    }
  })
}
