/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsCollectionIndexRouteImport } from './routes/collections/$collection/index'
import { Route as ApiCollectionIndexRouteImport } from './routes/api/$collection/index'
import { Route as CollectionsCollectionCreateRouteImport } from './routes/collections/$collection/create'
import { Route as CollectionsCollectionIdIndexRouteImport } from './routes/collections/$collection/$id/index'
import { Route as ApiCollectionIdIndexRouteImport } from './routes/api/$collection/$id/index'
import { Route as CollectionsCollectionIdHistoryRouteImport } from './routes/collections/$collection/$id/history'
import { Route as CollectionsCollectionIdApiRouteImport } from './routes/collections/$collection/$id/api'
import { Route as ApiCollectionIdPatchesRouteImport } from './routes/api/$collection/$id/patches'
import { Route as ApiCollectionIdHistoryRouteImport } from './routes/api/$collection/$id/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIndexRoute =
  CollectionsCollectionIndexRouteImport.update({
    id: '/collections/$collection/',
    path: '/collections/$collection/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCollectionIndexRoute = ApiCollectionIndexRouteImport.update({
  id: '/api/$collection/',
  path: '/api/$collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionCreateRoute =
  CollectionsCollectionCreateRouteImport.update({
    id: '/collections/$collection/create',
    path: '/collections/$collection/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCollectionIdIndexRoute =
  CollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collection/$id/',
    path: '/collections/$collection/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCollectionIdIndexRoute = ApiCollectionIdIndexRouteImport.update({
  id: '/api/$collection/$id/',
  path: '/api/$collection/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdHistoryRoute =
  CollectionsCollectionIdHistoryRouteImport.update({
    id: '/collections/$collection/$id/history',
    path: '/collections/$collection/$id/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCollectionIdApiRoute =
  CollectionsCollectionIdApiRouteImport.update({
    id: '/collections/$collection/$id/api',
    path: '/collections/$collection/$id/api',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCollectionIdPatchesRoute = ApiCollectionIdPatchesRouteImport.update({
  id: '/api/$collection/$id/patches',
  path: '/api/$collection/$id/patches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectionIdHistoryRoute = ApiCollectionIdHistoryRouteImport.update({
  id: '/api/$collection/$id/history',
  path: '/api/$collection/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections/$collection/create': typeof CollectionsCollectionCreateRoute
  '/api/$collection/': typeof ApiCollectionIndexRoute
  '/collections/$collection/': typeof CollectionsCollectionIndexRoute
  '/api/$collection/$id/history': typeof ApiCollectionIdHistoryRoute
  '/api/$collection/$id/patches': typeof ApiCollectionIdPatchesRoute
  '/collections/$collection/$id/api': typeof CollectionsCollectionIdApiRoute
  '/collections/$collection/$id/history': typeof CollectionsCollectionIdHistoryRoute
  '/api/$collection/$id/': typeof ApiCollectionIdIndexRoute
  '/collections/$collection/$id/': typeof CollectionsCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections/$collection/create': typeof CollectionsCollectionCreateRoute
  '/api/$collection': typeof ApiCollectionIndexRoute
  '/collections/$collection': typeof CollectionsCollectionIndexRoute
  '/api/$collection/$id/history': typeof ApiCollectionIdHistoryRoute
  '/api/$collection/$id/patches': typeof ApiCollectionIdPatchesRoute
  '/collections/$collection/$id/api': typeof CollectionsCollectionIdApiRoute
  '/collections/$collection/$id/history': typeof CollectionsCollectionIdHistoryRoute
  '/api/$collection/$id': typeof ApiCollectionIdIndexRoute
  '/collections/$collection/$id': typeof CollectionsCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections/$collection/create': typeof CollectionsCollectionCreateRoute
  '/api/$collection/': typeof ApiCollectionIndexRoute
  '/collections/$collection/': typeof CollectionsCollectionIndexRoute
  '/api/$collection/$id/history': typeof ApiCollectionIdHistoryRoute
  '/api/$collection/$id/patches': typeof ApiCollectionIdPatchesRoute
  '/collections/$collection/$id/api': typeof CollectionsCollectionIdApiRoute
  '/collections/$collection/$id/history': typeof CollectionsCollectionIdHistoryRoute
  '/api/$collection/$id/': typeof ApiCollectionIdIndexRoute
  '/collections/$collection/$id/': typeof CollectionsCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections/$collection/create'
    | '/api/$collection/'
    | '/collections/$collection/'
    | '/api/$collection/$id/history'
    | '/api/$collection/$id/patches'
    | '/collections/$collection/$id/api'
    | '/collections/$collection/$id/history'
    | '/api/$collection/$id/'
    | '/collections/$collection/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections/$collection/create'
    | '/api/$collection'
    | '/collections/$collection'
    | '/api/$collection/$id/history'
    | '/api/$collection/$id/patches'
    | '/collections/$collection/$id/api'
    | '/collections/$collection/$id/history'
    | '/api/$collection/$id'
    | '/collections/$collection/$id'
  id:
    | '__root__'
    | '/'
    | '/collections/$collection/create'
    | '/api/$collection/'
    | '/collections/$collection/'
    | '/api/$collection/$id/history'
    | '/api/$collection/$id/patches'
    | '/collections/$collection/$id/api'
    | '/collections/$collection/$id/history'
    | '/api/$collection/$id/'
    | '/collections/$collection/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsCollectionCreateRoute: typeof CollectionsCollectionCreateRoute
  ApiCollectionIndexRoute: typeof ApiCollectionIndexRoute
  CollectionsCollectionIndexRoute: typeof CollectionsCollectionIndexRoute
  ApiCollectionIdHistoryRoute: typeof ApiCollectionIdHistoryRoute
  ApiCollectionIdPatchesRoute: typeof ApiCollectionIdPatchesRoute
  CollectionsCollectionIdApiRoute: typeof CollectionsCollectionIdApiRoute
  CollectionsCollectionIdHistoryRoute: typeof CollectionsCollectionIdHistoryRoute
  ApiCollectionIdIndexRoute: typeof ApiCollectionIdIndexRoute
  CollectionsCollectionIdIndexRoute: typeof CollectionsCollectionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection/': {
      id: '/collections/$collection/'
      path: '/collections/$collection'
      fullPath: '/collections/$collection/'
      preLoaderRoute: typeof CollectionsCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$collection/': {
      id: '/api/$collection/'
      path: '/api/$collection'
      fullPath: '/api/$collection/'
      preLoaderRoute: typeof ApiCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection/create': {
      id: '/collections/$collection/create'
      path: '/collections/$collection/create'
      fullPath: '/collections/$collection/create'
      preLoaderRoute: typeof CollectionsCollectionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection/$id/': {
      id: '/collections/$collection/$id/'
      path: '/collections/$collection/$id'
      fullPath: '/collections/$collection/$id/'
      preLoaderRoute: typeof CollectionsCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$collection/$id/': {
      id: '/api/$collection/$id/'
      path: '/api/$collection/$id'
      fullPath: '/api/$collection/$id/'
      preLoaderRoute: typeof ApiCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection/$id/history': {
      id: '/collections/$collection/$id/history'
      path: '/collections/$collection/$id/history'
      fullPath: '/collections/$collection/$id/history'
      preLoaderRoute: typeof CollectionsCollectionIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection/$id/api': {
      id: '/collections/$collection/$id/api'
      path: '/collections/$collection/$id/api'
      fullPath: '/collections/$collection/$id/api'
      preLoaderRoute: typeof CollectionsCollectionIdApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$collection/$id/patches': {
      id: '/api/$collection/$id/patches'
      path: '/api/$collection/$id/patches'
      fullPath: '/api/$collection/$id/patches'
      preLoaderRoute: typeof ApiCollectionIdPatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$collection/$id/history': {
      id: '/api/$collection/$id/history'
      path: '/api/$collection/$id/history'
      fullPath: '/api/$collection/$id/history'
      preLoaderRoute: typeof ApiCollectionIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsCollectionCreateRoute: CollectionsCollectionCreateRoute,
  ApiCollectionIndexRoute: ApiCollectionIndexRoute,
  CollectionsCollectionIndexRoute: CollectionsCollectionIndexRoute,
  ApiCollectionIdHistoryRoute: ApiCollectionIdHistoryRoute,
  ApiCollectionIdPatchesRoute: ApiCollectionIdPatchesRoute,
  CollectionsCollectionIdApiRoute: CollectionsCollectionIdApiRoute,
  CollectionsCollectionIdHistoryRoute: CollectionsCollectionIdHistoryRoute,
  ApiCollectionIdIndexRoute: ApiCollectionIdIndexRoute,
  CollectionsCollectionIdIndexRoute: CollectionsCollectionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
