name: byline-postgres

services:
  db:
    image: postgres:latest
    container_name: byline_postgres
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data

  adminer:
    image: adminer
    profiles:
      - adminer
    ports:
      - 9000:8080
